# -*- coding: utf-8 -*-
"""Easy_Task_VAE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiEmhXGsKS7UD37Lr4oaRjFnHIVSDt7P

# Easy Task — Basic VAE for Music Clustering


1. Loads pre-extracted features from Google Drive (MFCC + lyrics embeddings)
2. Builds a unified hybrid dataset (audio features + language label)
3. Trains a fully-connected VAE on MFCC features
4. Performs K-Means clustering on the VAE latent space
5. Visualises clusters with t-SNE and UMAP
6. Compares with PCA + K-Means baseline using Silhouette Score and Calinski-Harabasz Index

## 0. Install dependencies
"""

!pip install -q umap-learn

"""## 1. Imports"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import silhouette_score, calinski_harabasz_score
from sklearn.manifold import TSNE

import umap

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')
print(f'PyTorch version: {torch.__version__}')

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)

"""## 2. Mount Drive and load features"""

from google.colab import drive
drive.mount('/content/drive')

FEAT_DIR = '/content/drive/MyDrive/VAE_Music_Project/features'
DATA_DIR = '/content/drive/MyDrive/VAE_Music_Project/data'

# Audio features (GTZAN — 1000 tracks, 80-dim MFCC)
X_train   = np.load(f'{FEAT_DIR}/X_train.npy')   # (800, 80)
X_test    = np.load(f'{FEAT_DIR}/X_test.npy')    # (200, 80)
y_train   = np.load(f'{FEAT_DIR}/y_train.npy', allow_pickle=True)
y_test    = np.load(f'{FEAT_DIR}/y_test.npy',  allow_pickle=True)

# Lyrics embeddings (Bollywood — 4101 songs, 384-dim)
hindi_emb   = np.load(f'{FEAT_DIR}/hindi_embeddings.npy')    # (4101, 384)
english_emb = np.load(f'{FEAT_DIR}/english_embeddings.npy')  # (4101, 384)

# Metadata
master_df = pd.read_csv(f'{DATA_DIR}/metadata.csv')
bollywood_df = pd.read_csv(f'{DATA_DIR}/bollywood_clean.csv')

print('=== Loaded features ===')
print(f'MFCC train : {X_train.shape}')
print(f'MFCC test  : {X_test.shape}')
print(f'Hindi emb  : {hindi_emb.shape}')
print(f'English emb: {english_emb.shape}')
print(f'Metadata   : {master_df.shape}')

"""## 3. Build the hybrid Easy-Task dataset

Need a *single* unified feature matrix that spans both English and Hindi/Bollywood content. This is done by:

1. Keeping all 1000 GTZAN MFCC vectors as-is (labelled `english`, genre label = genre name).
2. Projecting the 384-dim lyrics embeddings into the same 80-dim MFCC space using PCA — this is a lightweight alignment that lets us cluster audio and lyrics tracks together in one space without any paired data requirement.
3. Concatenating everything into one matrix `X_all` (shape ~9202 × 80) with matching label vectors.

This gives a  hybrid English + Hindi dataset with multiple label axes (genre, emotion, language).
"""

# ── Step 3a: Full GTZAN feature matrix (train + test reunited for clustering) ──
X_audio_all = np.vstack([X_train, X_test])          # (1000, 80)
y_genre_all = np.concatenate([y_train, y_test])      # (1000,)
lang_audio  = np.array(['english'] * 1000)
source_audio = np.array(['gtzan'] * 1000)

# ── Step 3b: Project lyrics embeddings → 80 dims via PCA ──

all_lyrics_emb = np.vstack([hindi_emb, english_emb])  # (8202, 384)

pca_lyrics = PCA(n_components=80, random_state=SEED)
all_lyrics_proj = pca_lyrics.fit_transform(all_lyrics_emb)  # (8202, 80)

hindi_proj   = all_lyrics_proj[:4101]   # (4101, 80)
english_proj = all_lyrics_proj[4101:]   # (4101, 80)

# Normalise projected lyrics to match MFCC scale
scaler_lyrics = StandardScaler()
all_lyrics_norm = scaler_lyrics.fit_transform(all_lyrics_proj)  # (8202, 80)
hindi_proj_norm   = all_lyrics_norm[:4101]
english_proj_norm = all_lyrics_norm[4101:]

# ── Step 3c: Build label arrays for Bollywood ── # Emotion labels from bollywood_clean.csv

emotion_labels = bollywood_df['emotion_category'].astype(str).values  # (4101,)

y_hindi   = emotion_labels           # (4101,)
y_english = emotion_labels           # same songs, English translation
lang_hindi   = np.array(['hindi']   * 4101)
lang_english = np.array(['english'] * 4101)
source_lyrics = np.array(['bollywood'] * 8202)

# ── Step 3d: Stack into master dataset ──
X_all     = np.vstack([X_audio_all, hindi_proj_norm, english_proj_norm])  # (9202, 80)
y_label   = np.concatenate([y_genre_all, y_hindi, y_english])             # (9202,)
y_lang    = np.concatenate([lang_audio, lang_hindi, lang_english])        # (9202,)
y_source  = np.concatenate([source_audio, source_lyrics])                 # (9202,)

print('=== Hybrid dataset ===')
print(f'X_all shape  : {X_all.shape}')
print(f'Language split:')
for lang, count in zip(*np.unique(y_lang, return_counts=True)):
    print(f'  {lang:10s}: {count}')
print(f'\nLabel types  :')
print(f'  GTZAN genres    : {np.unique(y_genre_all).tolist()}')
print(f'  Bollywood moods : {np.unique(y_hindi).tolist()}')
print(f'\nVariance explained by lyrics PCA: {pca_lyrics.explained_variance_ratio_.sum():.3f}')

"""## 4. VAE architecture"""

class Encoder(nn.Module):
    def __init__(self, input_dim, hidden_dims, latent_dim):
        super().__init__()
        layers = []
        prev = input_dim
        for h in hidden_dims:
            layers += [nn.Linear(prev, h), nn.BatchNorm1d(h), nn.LeakyReLU(0.2)]
            prev = h
        self.net  = nn.Sequential(*layers)
        self.mu   = nn.Linear(prev, latent_dim)
        self.logv = nn.Linear(prev, latent_dim)

    def forward(self, x):
        h = self.net(x)
        return self.mu(h), self.logv(h)


class Decoder(nn.Module):
    def __init__(self, latent_dim, hidden_dims, output_dim):
        super().__init__()
        layers = []
        prev = latent_dim
        for h in reversed(hidden_dims):
            layers += [nn.Linear(prev, h), nn.BatchNorm1d(h), nn.LeakyReLU(0.2)]
            prev = h
        layers.append(nn.Linear(prev, output_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, z):
        return self.net(z)


class VAE(nn.Module):
    def __init__(self, input_dim=80, hidden_dims=(256, 128), latent_dim=32):
        super().__init__()
        self.encoder = Encoder(input_dim, hidden_dims, latent_dim)
        self.decoder = Decoder(latent_dim, hidden_dims, input_dim)
        self.latent_dim = latent_dim

    def reparameterise(self, mu, logv):
        std = torch.exp(0.5 * logv)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x):
        mu, logv = self.encoder(x)
        z        = self.reparameterise(mu, logv)
        x_recon  = self.decoder(z)
        return x_recon, mu, logv

    def encode(self, x):
        """Return mu only (deterministic latent representation)."""
        mu, _ = self.encoder(x)
        return mu


def vae_loss(x, x_recon, mu, logv, beta=1.0):
    """ELBO = MSE reconstruction + beta * KL divergence."""
    recon_loss = nn.functional.mse_loss(x_recon, x, reduction='mean')
    kl_loss    = -0.5 * torch.mean(1 + logv - mu.pow(2) - logv.exp())
    return recon_loss + beta * kl_loss, recon_loss, kl_loss


# Instantiate
INPUT_DIM  = 80
HIDDEN     = (256, 128)
LATENT_DIM = 32

model = VAE(input_dim=INPUT_DIM, hidden_dims=HIDDEN, latent_dim=LATENT_DIM).to(device)
print(model)
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'\nTrainable parameters: {total_params:,}')

"""## 5. Train the VAE"""

# ── Hyperparameters ──
EPOCHS     = 100
BATCH_SIZE = 256
LR         = 1e-3
BETA       = 1.0   # standard VAE; increase for Beta-VAE in Hard Task

# ── DataLoader — train on full hybrid dataset ──
X_tensor   = torch.tensor(X_all, dtype=torch.float32)
dataset    = TensorDataset(X_tensor)
loader     = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True,
                        num_workers=0, pin_memory=True)

optimizer  = optim.Adam(model.parameters(), lr=LR, weight_decay=1e-5)
scheduler  = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

# ── Training loop ──
history = {'total': [], 'recon': [], 'kl': []}

model.train()
for epoch in range(1, EPOCHS + 1):
    ep_total = ep_recon = ep_kl = 0.0
    for (xb,) in loader:
        xb = xb.to(device)
        optimizer.zero_grad()
        x_recon, mu, logv = model(xb)
        loss, recon, kl   = vae_loss(xb, x_recon, mu, logv, beta=BETA)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        ep_total += loss.item()
        ep_recon += recon.item()
        ep_kl    += kl.item()
    scheduler.step()

    n = len(loader)
    history['total'].append(ep_total / n)
    history['recon'].append(ep_recon / n)
    history['kl'].append(ep_kl / n)

    if epoch % 10 == 0 or epoch == 1:
        print(f'Epoch {epoch:3d}/{EPOCHS} | '
              f'Total: {history["total"][-1]:.4f} | '
              f'Recon: {history["recon"][-1]:.4f} | '
              f'KL: {history["kl"][-1]:.4f}')

print('\nTraining complete.')

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
titles  = ['Total ELBO Loss', 'Reconstruction Loss', 'KL Divergence']
keys    = ['total', 'recon', 'kl']
colours = ['#3B6FCC', '#D85A30', '#1D9E75']

for ax, title, key, c in zip(axes, titles, keys, colours):
    ax.plot(history[key], color=c, linewidth=1.8)
    ax.set_title(title, fontsize=13)
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Loss')
    ax.grid(alpha=0.3)
    ax.spines[['top','right']].set_visible(False)

plt.suptitle('VAE Training Curves', fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
os.makedirs('results/easy_task', exist_ok=True)
plt.savefig('results/easy_task/training_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/easy_task/training_curves.png')

"""## 6. Extract latent representations"""

model.eval()
with torch.no_grad():
    Z_all = model.encode(
        torch.tensor(X_all, dtype=torch.float32).to(device)
    ).cpu().numpy()  # (9202, 32)

print(f'Latent vectors shape: {Z_all.shape}')
print(f'Mean: {Z_all.mean():.4f} | Std: {Z_all.std():.4f}')


np.save('results/easy_task/Z_all.npy', Z_all)
np.save('results/easy_task/y_label.npy', y_label)
np.save('results/easy_task/y_lang.npy',  y_lang)
print('Latent vectors saved.')

"""## 7. K-Means clustering on VAE latent space"""

# ── Elbow plot to choose k ──
inertias = []
K_range  = range(2, 21)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=SEED, n_init=10)
    km.fit(Z_all)
    inertias.append(km.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(list(K_range), inertias, 'o-', color='#3B6FCC', linewidth=2, markersize=6)
plt.axvline(x=10, color='#D85A30', linestyle='--', linewidth=1.5, label='k=10 (GTZAN genres)')
plt.xlabel('Number of clusters k')
plt.ylabel('Inertia')
plt.title('Elbow Plot — VAE Latent Space', fontsize=13)
plt.legend()
plt.grid(alpha=0.3)
plt.spines = plt.gca().spines
plt.gca().spines[['top','right']].set_visible(False)
plt.tight_layout()
plt.savefig('results/easy_task/elbow_plot.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/easy_task/elbow_plot.png')

# ── Fit K-Means with k=10 (matches number of GTZAN genres) ──
K = 10
kmeans = KMeans(n_clusters=K, random_state=SEED, n_init=20, max_iter=500)
cluster_labels = kmeans.fit_predict(Z_all)  # (9202,)

# Cluster size distribution
unique, counts = np.unique(cluster_labels, return_counts=True)
print('=== K-Means cluster sizes ===')
for c, n in zip(unique, counts):
    print(f'  Cluster {c:2d}: {n:5d} samples')

np.save('results/easy_task/cluster_labels_vae.npy', cluster_labels)

"""## 8. t-SNE and UMAP visualisations"""

print('Running t-SNE on latent vectors (this may take ~2 minutes)...')
tsne = TSNE(n_components=2, perplexity=40, learning_rate='auto',
            init='pca', random_state=SEED, n_iter=1000)
Z_tsne = tsne.fit_transform(Z_all)   # (9202, 2)
print(f't-SNE done. Shape: {Z_tsne.shape}')
np.save('results/easy_task/Z_tsne.npy', Z_tsne)

print('Running UMAP on latent vectors...')
reducer = umap.UMAP(n_components=2, n_neighbors=30, min_dist=0.1,
                    random_state=SEED, metric='euclidean')
Z_umap = reducer.fit_transform(Z_all)   # (9202, 2)
print(f'UMAP done. Shape: {Z_umap.shape}')
np.save('results/easy_task/Z_umap.npy', Z_umap)

# ── Colour palettes ──
CLUSTER_PALETTE = [
    '#E24B4A','#378ADD','#1D9E75','#EF9F27','#7F77DD',
    '#D85A30','#639922','#D4537E','#185FA5','#5F5E5A'
]
LANG_PALETTE = {'english': '#378ADD', 'hindi': '#D85A30'}

GENRE_PALETTE = {
    'blues':'#185FA5','classical':'#7F77DD','country':'#639922',
    'disco':'#D4537E','hiphop':'#5F5E5A','jazz':'#1D9E75',
    'metal':'#E24B4A','pop':'#EF9F27','reggae':'#D85A30','rock':'#3B6FCC'
}
MOOD_PALETTE = {
    'very_sad':'#042C53','sad':'#378ADD','neutral':'#888780',
    'happy':'#EF9F27','very_happy':'#D85A30'
}

# Combine genre + mood palettes for all label types
LABEL_PALETTE = {**GENRE_PALETTE, **MOOD_PALETTE}

def scatter(ax, embed, c_arr, title, alpha=0.25, s=4):
    ax.scatter(embed[:, 0], embed[:, 1], c=c_arr, s=s, alpha=alpha, linewidths=0)
    ax.set_title(title, fontsize=11)
    ax.set_xlabel('Dim 1'); ax.set_ylabel('Dim 2')
    ax.spines[['top','right']].set_visible(False)

# ── Figure 1: t-SNE — 4 views ──
fig, axes = plt.subplots(2, 2, figsize=(16, 14))

# (A) t-SNE coloured by K-Means cluster
c_cluster = [CLUSTER_PALETTE[l] for l in cluster_labels]
scatter(axes[0,0], Z_tsne, c_cluster, '(A) t-SNE — K-Means clusters')
patches = [mpatches.Patch(color=CLUSTER_PALETTE[i], label=f'Cluster {i}') for i in range(K)]
axes[0,0].legend(handles=patches, fontsize=7, ncol=2, loc='upper right')

# (B) t-SNE coloured by language
c_lang = [LANG_PALETTE[l] for l in y_lang]
scatter(axes[0,1], Z_tsne, c_lang, '(B) t-SNE — Language')
patches_lang = [mpatches.Patch(color=v, label=k) for k, v in LANG_PALETTE.items()]
axes[0,1].legend(handles=patches_lang, fontsize=9)

# (C) t-SNE coloured by label (genre for GTZAN, mood for Bollywood)
c_label = [LABEL_PALETTE.get(l, '#888780') for l in y_label]
scatter(axes[1,0], Z_tsne, c_label, '(C) t-SNE — Genre / Mood label')
patches_lbl = [mpatches.Patch(color=v, label=k) for k, v in LABEL_PALETTE.items()]
axes[1,0].legend(handles=patches_lbl, fontsize=7, ncol=2, loc='upper right')

# (D) t-SNE — GTZAN only, coloured by genre
gtzan_mask = y_source == 'gtzan'
c_genre_gtzan = [GENRE_PALETTE.get(l, '#888780') for l in y_label[gtzan_mask]]
axes[1,1].scatter(Z_tsne[gtzan_mask, 0], Z_tsne[gtzan_mask, 1],
                  c=c_genre_gtzan, s=10, alpha=0.7, linewidths=0)
axes[1,1].set_title('(D) t-SNE — GTZAN only, by genre', fontsize=11)
axes[1,1].set_xlabel('Dim 1'); axes[1,1].set_ylabel('Dim 2')
axes[1,1].spines[['top','right']].set_visible(False)
patches_g = [mpatches.Patch(color=v, label=k) for k, v in GENRE_PALETTE.items()]
axes[1,1].legend(handles=patches_g, fontsize=7, ncol=2, loc='upper right')

plt.suptitle('t-SNE Visualisations — VAE Latent Space (Easy Task)', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('results/easy_task/tsne_plots.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/easy_task/tsne_plots.png')

# ── Figure 2: UMAP — 4 views ──
fig, axes = plt.subplots(2, 2, figsize=(16, 14))

scatter(axes[0,0], Z_umap, c_cluster, '(A) UMAP — K-Means clusters')
axes[0,0].legend(handles=patches, fontsize=7, ncol=2)

scatter(axes[0,1], Z_umap, c_lang,    '(B) UMAP — Language')
axes[0,1].legend(handles=patches_lang, fontsize=9)

scatter(axes[1,0], Z_umap, c_label,   '(C) UMAP — Genre / Mood label')
axes[1,0].legend(handles=patches_lbl, fontsize=7, ncol=2)

axes[1,1].scatter(Z_umap[gtzan_mask, 0], Z_umap[gtzan_mask, 1],
                  c=c_genre_gtzan, s=10, alpha=0.7, linewidths=0)
axes[1,1].set_title('(D) UMAP — GTZAN only, by genre', fontsize=11)
axes[1,1].set_xlabel('Dim 1'); axes[1,1].set_ylabel('Dim 2')
axes[1,1].spines[['top','right']].set_visible(False)
axes[1,1].legend(handles=patches_g, fontsize=7, ncol=2)

plt.suptitle('UMAP Visualisations — VAE Latent Space (Easy Task)', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('results/easy_task/umap_plots.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/easy_task/umap_plots.png')

"""## 9. Baseline — PCA + K-Means"""

# ── PCA baseline: reduce X_all to 32 dims (same as VAE latent), then K-Means ──
pca_baseline = PCA(n_components=32, random_state=SEED)
Z_pca        = pca_baseline.fit_transform(X_all)   # (9202, 32)

kmeans_pca   = KMeans(n_clusters=K, random_state=SEED, n_init=20, max_iter=500)
pca_clusters = kmeans_pca.fit_predict(Z_pca)

print(f'PCA variance explained (32 dims): {pca_baseline.explained_variance_ratio_.sum():.3f}')
print(f'PCA cluster sizes:')
for c, n in zip(*np.unique(pca_clusters, return_counts=True)):
    print(f'  Cluster {c:2d}: {n:5d}')

np.save('results/easy_task/cluster_labels_pca.npy', pca_clusters)

"""## 10. Evaluation metrics"""

# ── Compute metrics for VAE and PCA on both the full dataset and GTZAN-only subset ──

def evaluate(Z, labels, name):
    sil = silhouette_score(Z, labels, sample_size=5000, random_state=SEED)
    ch  = calinski_harabasz_score(Z, labels)
    return {'method': name, 'silhouette': round(sil, 4), 'calinski_harabasz': round(ch, 2)}

results = []

# Full dataset
results.append(evaluate(Z_all, cluster_labels, 'VAE + K-Means (full)'))
results.append(evaluate(X_all, pca_clusters,   'PCA + K-Means (full)'))

# GTZAN-only subset (cleaner evaluation since it has real genre labels)
Z_gtzan = Z_all[gtzan_mask]
X_gtzan = X_all[gtzan_mask]
y_gtzan = y_label[gtzan_mask]

# Re-cluster on GTZAN subset only
km_gtzan_vae = KMeans(n_clusters=10, random_state=SEED, n_init=20).fit(Z_gtzan)
km_gtzan_pca = KMeans(n_clusters=10, random_state=SEED, n_init=20).fit(X_gtzan)

results.append(evaluate(Z_gtzan, km_gtzan_vae.labels_, 'VAE + K-Means (GTZAN only)'))
results.append(evaluate(X_gtzan, km_gtzan_pca.labels_, 'PCA + K-Means (GTZAN only)'))

results_df = pd.DataFrame(results)
print('\n=== Clustering Evaluation — Easy Task ===')
print(results_df.to_string(index=False))

results_df.to_csv('results/easy_task/clustering_metrics.csv', index=False)
print('\nSaved: results/easy_task/clustering_metrics.csv')

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

methods   = results_df['method'].tolist()
short_lbl = ['VAE\n(full)', 'PCA\n(full)', 'VAE\n(GTZAN)', 'PCA\n(GTZAN)']
colours   = ['#378ADD', '#D85A30', '#1D9E75', '#EF9F27']

# Silhouette
bars0 = axes[0].bar(short_lbl, results_df['silhouette'], color=colours, edgecolor='white', width=0.5)
axes[0].set_title('Silhouette Score\n(higher = better)', fontsize=12)
axes[0].set_ylabel('Score')
axes[0].set_ylim(0, max(results_df['silhouette']) * 1.3)
for bar, val in zip(bars0, results_df['silhouette']):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
                 f'{val:.4f}', ha='center', va='bottom', fontsize=9)
axes[0].spines[['top','right']].set_visible(False)

# Calinski-Harabasz
bars1 = axes[1].bar(short_lbl, results_df['calinski_harabasz'], color=colours, edgecolor='white', width=0.5)
axes[1].set_title('Calinski-Harabasz Index\n(higher = better)', fontsize=12)
axes[1].set_ylabel('Score')
for bar, val in zip(bars1, results_df['calinski_harabasz']):
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                 f'{val:.0f}', ha='center', va='bottom', fontsize=9)
axes[1].spines[['top','right']].set_visible(False)

plt.suptitle('VAE vs PCA Baseline — Clustering Metrics (Easy Task)', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('results/easy_task/metrics_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/easy_task/metrics_comparison.png')

"""## 11. Cluster composition analysis"""

# ── What does each VAE cluster contain? ──
# Focus on GTZAN subset where labels are meaningful genre names

gtzan_cluster_labels = km_gtzan_vae.labels_
gtzan_genre_labels   = y_gtzan

comp_df = pd.DataFrame({'cluster': gtzan_cluster_labels, 'genre': gtzan_genre_labels})
pivot   = comp_df.groupby(['cluster','genre']).size().unstack(fill_value=0)

fig, ax = plt.subplots(figsize=(14, 5))
pivot.plot(kind='bar', ax=ax, colormap='tab10', edgecolor='white', width=0.8)
ax.set_title('Cluster Composition by Genre — VAE (GTZAN only)', fontsize=13)
ax.set_xlabel('Cluster')
ax.set_ylabel('Track count')
ax.set_xticklabels(ax.get_xticklabels(), rotation=0)
ax.legend(title='Genre', bbox_to_anchor=(1.01, 1), fontsize=8)
ax.spines[['top','right']].set_visible(False)
plt.tight_layout()
plt.savefig('results/easy_task/cluster_composition.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/easy_task/cluster_composition.png')

print('\n=== Dominant genre per cluster ===')
for cluster_id, row in pivot.iterrows():
    dominant = row.idxmax()
    pct      = row.max() / row.sum() * 100
    print(f'  Cluster {cluster_id:2d}: dominant={dominant:12s}  ({pct:.0f}%)')

"""## 12. Save model and results to Drive"""

import shutil

SAVE_DIR = '/content/drive/MyDrive/VAE_Music_Project/results/easy_task'
os.makedirs(SAVE_DIR, exist_ok=True)

# Save model weights
torch.save(model.state_dict(), f'{SAVE_DIR}/vae_easy_task.pth')

# Copy result files
for fname in os.listdir('results/easy_task'):
    src = f'results/easy_task/{fname}'
    shutil.copy(src, f'{SAVE_DIR}/{fname}')

print('=== All results saved to Drive ===')
for f in sorted(os.listdir(SAVE_DIR)):
    size = os.path.getsize(f'{SAVE_DIR}/{f}') / 1024
    print(f'  {f:40s}  {size:.1f} KB')

"""## 13. Easy Task summary"""

print('=' * 60)
print('EASY TASK COMPLETE — SUMMARY')
print('=' * 60)

print(f'''
Dataset
  Total samples       : {len(X_all):,}
  English tracks      : {(y_lang == "english").sum():,}  (GTZAN audio + Bollywood EN translations)
  Hindi tracks        : {(y_lang == "hindi").sum():,}  (Bollywood Hindi lyrics)
  Feature dimension   : {X_all.shape[1]}

VAE Architecture
  Input dim           : {INPUT_DIM}
  Hidden layers       : {HIDDEN}
  Latent dim          : {LATENT_DIM}
  Training epochs     : {EPOCHS}
  Batch size          : {BATCH_SIZE}
  Beta (KL weight)    : {BETA}

Clustering
  Algorithm           : K-Means (k=10)
  Representation      : VAE mu vectors (32-dim)

Evaluation
''')
print(results_df.to_string(index=False))

print('''
Outputs saved
  results/easy_task/training_curves.png
  results/easy_task/elbow_plot.png
  results/easy_task/tsne_plots.png
  results/easy_task/umap_plots.png
  results/easy_task/metrics_comparison.png
  results/easy_task/cluster_composition.png
  results/easy_task/clustering_metrics.csv
  results/easy_task/Z_all.npy
  results/easy_task/vae_easy_task.pth  (on Drive)
''')