# -*- coding: utf-8 -*-
"""easy_task_part2_current_dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_eZGyt9Napbscx6CD45oDv-De37ooNKi

# Easy Task — Basic VAE for Hybrid Language Music Clustering

This notebook implements the **Easy Task** using gtzan audio+lyrics and a bollywood dataset .

## Dataset used

- GTZAN Whisper pseudo-lyrics: English / pseudo-English text generated from GTZAN audio
- Bollywood Hindi lyrics: Hindi text
- Feature matrix: multilingual SentenceTransformer lyrics embeddings
- Current expected shape from your run: approximately `(837, 384)`

## Easy Task requirements covered

1. Basic VAE for feature extraction
2. Small hybrid language dataset
3. K-Means clustering on VAE latent features
4. t-SNE and UMAP visualization
5. PCA + K-Means baseline comparison using:
   - Silhouette Score
   - Calinski-Harabasz Index

## 1. Mount Drive and install dependencies
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q umap-learn pandas numpy scikit-learn matplotlib torch

"""## 2. Imports and paths"""

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, calinski_harabasz_score
from sklearn.manifold import TSNE
import umap

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

PROJECT_DIR = "/content/drive/MyDrive/VAE_Music_Project"
PART2_DIR = f"{PROJECT_DIR}/features_part2"
RESULTS_DIR = f"{PROJECT_DIR}/results/easy_task_part2"

os.makedirs(RESULTS_DIR, exist_ok=True)

print("PART2_DIR:", PART2_DIR)
print("RESULTS_DIR:", RESULTS_DIR)

"""## 3. Load current hybrid-language dataset"""

META_PATH = f"{PART2_DIR}/metadata_part2_gtzan500_hindi500.csv"
EMB_PATH  = f"{PART2_DIR}/all1000_lyrics_embeddings.npy"

if not os.path.exists(META_PATH):
    raise FileNotFoundError(f"Metadata file not found: {META_PATH}")

if not os.path.exists(EMB_PATH):
    raise FileNotFoundError(f"Embedding file not found: {EMB_PATH}")

metadata = pd.read_csv(META_PATH)
X_raw = np.load(EMB_PATH)

print("Metadata shape:", metadata.shape)
print("Embedding shape:", X_raw.shape)
print("\nColumns:", metadata.columns.tolist())
print("\nLanguage counts:")
print(metadata["language"].value_counts())
print("\nSource counts:")
print(metadata["source"].value_counts())

metadata.head()

"""## 4. Prepare labels and normalize features"""

# Main clustering label for Easy Task: language
# This directly checks whether VAE separates English/GTZAN pseudo-lyrics and Hindi lyrics.
y_lang = metadata["language"].astype(str).values
y_source = metadata["source"].astype(str).values
y_genre = metadata["genre_label"].astype(str).values

le_lang = LabelEncoder()
y_lang_enc = le_lang.fit_transform(y_lang)

print("Language classes:", list(le_lang.classes_))

# Normalize embeddings before VAE training
scaler = StandardScaler()
X_all = scaler.fit_transform(X_raw).astype(np.float32)

print("Final X_all shape:", X_all.shape)
print("Feature dimension:", X_all.shape[1])

"""## 5. Define basic fully-connected VAE"""

class Encoder(nn.Module):
    def __init__(self, input_dim, hidden_dims, latent_dim):
        super().__init__()
        layers = []
        prev = input_dim

        for h in hidden_dims:
            layers.append(nn.Linear(prev, h))
            layers.append(nn.BatchNorm1d(h))
            layers.append(nn.LeakyReLU(0.2))
            prev = h

        self.net = nn.Sequential(*layers)
        self.mu = nn.Linear(prev, latent_dim)
        self.logv = nn.Linear(prev, latent_dim)

    def forward(self, x):
        h = self.net(x)
        return self.mu(h), self.logv(h)


class Decoder(nn.Module):
    def __init__(self, latent_dim, hidden_dims, output_dim):
        super().__init__()
        layers = []
        prev = latent_dim

        for h in reversed(hidden_dims):
            layers.append(nn.Linear(prev, h))
            layers.append(nn.BatchNorm1d(h))
            layers.append(nn.LeakyReLU(0.2))
            prev = h

        layers.append(nn.Linear(prev, output_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, z):
        return self.net(z)


class BasicVAE(nn.Module):
    def __init__(self, input_dim=384, hidden_dims=(256, 128), latent_dim=32):
        super().__init__()
        self.encoder = Encoder(input_dim, hidden_dims, latent_dim)
        self.decoder = Decoder(latent_dim, hidden_dims, input_dim)

    def reparameterize(self, mu, logv):
        std = torch.exp(0.5 * logv)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x):
        mu, logv = self.encoder(x)
        z = self.reparameterize(mu, logv)
        x_recon = self.decoder(z)
        return x_recon, mu, logv

    def encode(self, x):
        mu, _ = self.encoder(x)
        return mu


def vae_loss(x, x_recon, mu, logv, beta=1.0):
    recon_loss = nn.functional.mse_loss(x_recon, x, reduction="mean")
    kl_loss = -0.5 * torch.mean(1 + logv - mu.pow(2) - logv.exp())
    total = recon_loss + beta * kl_loss
    return total, recon_loss, kl_loss

"""## 6. Train VAE"""

INPUT_DIM = X_all.shape[1]
HIDDEN_DIMS = (256, 128)
LATENT_DIM = 32

EPOCHS = 100
BATCH_SIZE = 128
LR = 1e-3
BETA = 1.0

model = BasicVAE(
    input_dim=INPUT_DIM,
    hidden_dims=HIDDEN_DIMS,
    latent_dim=LATENT_DIM
).to(device)

X_tensor = torch.tensor(X_all, dtype=torch.float32)
dataset = TensorDataset(X_tensor)
loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

optimizer = optim.Adam(model.parameters(), lr=LR, weight_decay=1e-5)

history = {
    "total": [],
    "recon": [],
    "kl": []
}

model.train()

for epoch in range(1, EPOCHS + 1):
    total_epoch = 0.0
    recon_epoch = 0.0
    kl_epoch = 0.0

    for (xb,) in loader:
        xb = xb.to(device)

        optimizer.zero_grad()
        x_recon, mu, logv = model(xb)
        loss, recon, kl = vae_loss(xb, x_recon, mu, logv, beta=BETA)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        total_epoch += loss.item()
        recon_epoch += recon.item()
        kl_epoch += kl.item()

    n_batches = len(loader)
    history["total"].append(total_epoch / n_batches)
    history["recon"].append(recon_epoch / n_batches)
    history["kl"].append(kl_epoch / n_batches)

    if epoch == 1 or epoch % 10 == 0:
        print(
            f"Epoch {epoch:03d}/{EPOCHS} | "
            f"Total={history['total'][-1]:.4f} | "
            f"Recon={history['recon'][-1]:.4f} | "
            f"KL={history['kl'][-1]:.4f}"
        )

print("Training complete.")

"""## 7. Plot training curves"""

plt.figure(figsize=(8, 5))
plt.plot(history["total"], label="Total loss")
plt.plot(history["recon"], label="Reconstruction loss")
plt.plot(history["kl"], label="KL loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Easy Task VAE Training Curves")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()

training_curve_path = f"{RESULTS_DIR}/training_curves.png"
plt.savefig(training_curve_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", training_curve_path)

"""## 8. Extract VAE latent features"""

model.eval()

with torch.no_grad():
    Z_vae = model.encode(
        torch.tensor(X_all, dtype=torch.float32).to(device)
    ).cpu().numpy()

print("VAE latent shape:", Z_vae.shape)

np.save(f"{RESULTS_DIR}/Z_vae_easy_task.npy", Z_vae)
torch.save(model.state_dict(), f"{RESULTS_DIR}/basic_vae_easy_task.pth")

print("Saved latent features and model.")

"""## 9. K-Means clustering on VAE latent space"""

# Since current dataset has 2 languages, k=2 is appropriate for language-level clustering.
# We also keep k=10 optional later if you want genre-like cluster exploration.
N_CLUSTERS = len(np.unique(y_lang))

kmeans_vae = KMeans(n_clusters=N_CLUSTERS, random_state=SEED, n_init=10)
clusters_vae = kmeans_vae.fit_predict(Z_vae)

sil_vae = silhouette_score(Z_vae, clusters_vae)
ch_vae = calinski_harabasz_score(Z_vae, clusters_vae)

print("VAE + K-Means")
print("n_clusters:", N_CLUSTERS)
print("Silhouette Score:", sil_vae)
print("Calinski-Harabasz Index:", ch_vae)

"""## 10. PCA + K-Means baseline"""

# PCA baseline with the same latent dimension as VAE
pca = PCA(n_components=LATENT_DIM, random_state=SEED)
Z_pca = pca.fit_transform(X_all)

kmeans_pca = KMeans(n_clusters=N_CLUSTERS, random_state=SEED, n_init=10)
clusters_pca = kmeans_pca.fit_predict(Z_pca)

sil_pca = silhouette_score(Z_pca, clusters_pca)
ch_pca = calinski_harabasz_score(Z_pca, clusters_pca)

print("PCA + K-Means")
print("n_clusters:", N_CLUSTERS)
print("Silhouette Score:", sil_pca)
print("Calinski-Harabasz Index:", ch_pca)
print("PCA variance explained:", pca.explained_variance_ratio_.sum())

"""## 11. Metrics comparison table"""

metrics_df = pd.DataFrame([
    {
        "method": "VAE + K-Means",
        "representation": "VAE latent mu",
        "n_clusters": N_CLUSTERS,
        "silhouette": sil_vae,
        "calinski_harabasz": ch_vae
    },
    {
        "method": "PCA + K-Means",
        "representation": "PCA features",
        "n_clusters": N_CLUSTERS,
        "silhouette": sil_pca,
        "calinski_harabasz": ch_pca
    }
])

metrics_path = f"{RESULTS_DIR}/easy_task_metrics.csv"
metrics_df.to_csv(metrics_path, index=False)

print("Saved:", metrics_path)
metrics_df

"""## 12. Plot metrics comparison"""

fig, axes = plt.subplots(1, 2, figsize=(11, 4))

axes[0].bar(metrics_df["method"], metrics_df["silhouette"])
axes[0].set_title("Silhouette Score")
axes[0].set_ylabel("Score")
axes[0].tick_params(axis="x", rotation=20)

axes[1].bar(metrics_df["method"], metrics_df["calinski_harabasz"])
axes[1].set_title("Calinski-Harabasz Index")
axes[1].set_ylabel("Score")
axes[1].tick_params(axis="x", rotation=20)

plt.suptitle("Easy Task: VAE vs PCA Baseline")
plt.tight_layout()

metric_plot_path = f"{RESULTS_DIR}/metrics_comparison.png"
plt.savefig(metric_plot_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", metric_plot_path)

"""## 13. t-SNE visualization"""

tsne = TSNE(
    n_components=2,
    random_state=SEED,
    perplexity=30,
    init="pca",
    learning_rate="auto"
)

Z_tsne = tsne.fit_transform(Z_vae)

tsne_df = pd.DataFrame({
    "x": Z_tsne[:, 0],
    "y": Z_tsne[:, 1],
    "language": y_lang,
    "source": y_source,
    "cluster": clusters_vae
})

plt.figure(figsize=(8, 6))

for lang in sorted(tsne_df["language"].unique()):
    sub = tsne_df[tsne_df["language"] == lang]
    plt.scatter(sub["x"], sub["y"], s=18, alpha=0.75, label=lang)

plt.title("t-SNE of VAE Latent Space by Language")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.legend()
plt.grid(alpha=0.25)
plt.tight_layout()

tsne_path = f"{RESULTS_DIR}/tsne_language.png"
plt.savefig(tsne_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", tsne_path)

"""## 14. UMAP visualization"""

umap_model = umap.UMAP(
    n_components=2,
    random_state=SEED,
    n_neighbors=15,
    min_dist=0.1
)

Z_umap = umap_model.fit_transform(Z_vae)

umap_df = pd.DataFrame({
    "x": Z_umap[:, 0],
    "y": Z_umap[:, 1],
    "language": y_lang,
    "source": y_source,
    "cluster": clusters_vae
})

plt.figure(figsize=(8, 6))

for lang in sorted(umap_df["language"].unique()):
    sub = umap_df[umap_df["language"] == lang]
    plt.scatter(sub["x"], sub["y"], s=18, alpha=0.75, label=lang)

plt.title("UMAP of VAE Latent Space by Language")
plt.xlabel("UMAP 1")
plt.ylabel("UMAP 2")
plt.legend()
plt.grid(alpha=0.25)
plt.tight_layout()

umap_path = f"{RESULTS_DIR}/umap_language.png"
plt.savefig(umap_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", umap_path)

"""## 15. Cluster composition"""

cluster_df = pd.DataFrame({
    "cluster": clusters_vae,
    "language": y_lang,
    "source": y_source,
    "genre_label": y_genre
})

cluster_language = pd.crosstab(cluster_df["cluster"], cluster_df["language"])
cluster_source = pd.crosstab(cluster_df["cluster"], cluster_df["source"])

cluster_language_path = f"{RESULTS_DIR}/cluster_language_composition.csv"
cluster_source_path = f"{RESULTS_DIR}/cluster_source_composition.csv"

cluster_language.to_csv(cluster_language_path)
cluster_source.to_csv(cluster_source_path)

print("Cluster × Language")
display(cluster_language)

print("\nCluster × Source")
display(cluster_source)

print("\nSaved:")
print(cluster_language_path)
print(cluster_source_path)

"""## 16. Final summary"""

print("=" * 60)
print("EASY TASK COMPLETE — SUMMARY")
print("=" * 60)

print(f'''
Dataset
  Total samples       : {len(X_all):,}
  English / GTZAN     : {(y_lang == "english").sum():,}
  Hindi               : {(y_lang == "hindi").sum():,}
  Feature dimension   : {X_all.shape[1]}

VAE Architecture
  Input dim           : {INPUT_DIM}
  Hidden layers       : {HIDDEN_DIMS}
  Latent dim          : {LATENT_DIM}
  Training epochs     : {EPOCHS}
  Batch size          : {BATCH_SIZE}
  Beta / KL weight    : {BETA}

Clustering
  Algorithm           : K-Means
  Number of clusters  : {N_CLUSTERS}
  Representation      : VAE mu vectors ({LATENT_DIM}-dim)

Evaluation
{metrics_df.to_string(index=False)}

Outputs saved to:
  {RESULTS_DIR}
''')

"""

> For the Easy Task, we trained a basic fully connected VAE on multilingual lyric embeddings from GTZAN Whisper pseudo-lyrics and Hindi song lyrics. K-Means was applied to the learned latent mean vectors, and performance was compared with a PCA + K-Means baseline using Silhouette Score and Calinski-Harabasz Index.


> GTZAN lyrics are Whisper-generated pseudo-lyrics and may contain transcription noise due to instrumental interference.
"""