# -*- coding: utf-8 -*-
"""Feature extraction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HUUgmiuFJNsnLyPSbmjZlt6vhTbNj2Gg

Mount Drive and restore data
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np


os.makedirs('data/audio', exist_ok=True)
os.makedirs('data/mfcc', exist_ok=True)
os.makedirs('data/spectrograms', exist_ok=True)
os.makedirs('data/embeddings', exist_ok=True)
os.makedirs('results', exist_ok=True)

save_dir  = '/content/drive/MyDrive/VAE_Music_Project/data'
drive_base = '/content/drive/MyDrive/VAE_Music_Project/raw_data'


master    = pd.read_csv(f'{save_dir}/metadata.csv')
gtzan_df  = pd.read_csv(f'{save_dir}/gtzan_index.csv')
df        = pd.read_csv(f'{save_dir}/bollywood_clean.csv')

print("master shape   :", master.shape)
print("gtzan_df shape :", gtzan_df.shape)
print("df shape       :", df.shape)

"""Re-extract GTZAN zip (audio files need to be local)"""

import zipfile

gtzan_zip = f'{drive_base}/gtzan.zip'

print("Extracting GTZAN audio files...")
with zipfile.ZipFile(gtzan_zip, 'r') as z:
    z.extractall('data/audio')
print("Done.")

# Verify
count = sum(1 for r, d, files in os.walk('data/audio') for f in files if f.endswith('.au'))
print(f"Audio files available: {count}")

"""Extract MFCC features from all 1000 tracks"""

import librosa
import numpy as np
from tqdm import tqdm

MFCC_DIR = 'data/mfcc'
N_MFCC   = 40
SR       = 22050
DURATION = 30  # seconds

mfcc_records = []
failed       = []

print(f"Extracting MFCCs from {len(gtzan_df)} tracks...")

for idx, row in tqdm(gtzan_df.iterrows(), total=len(gtzan_df)):
    filepath = row['filepath']
    filename = row['filename']
    genre    = row['genre']

    try:

        y, sr = librosa.load(filepath, sr=SR, duration=DURATION)

        # Extract MFCC — shape (40, T)
        mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=N_MFCC)

        # Take mean across time → shape (40,) — one vector per track
        mfcc_mean = mfcc.mean(axis=1)

        # Also store std for richer features
        mfcc_std  = mfcc.std(axis=1)

        # Concatenate mean + std → shape (80,)
        mfcc_combined = np.concatenate([mfcc_mean, mfcc_std])


        save_name = filename.replace('.au', '.npy')
        save_path = os.path.join(MFCC_DIR, save_name)
        np.save(save_path, mfcc_combined)

        mfcc_records.append({
            'filename'  : filename,
            'genre'     : genre,
            'mfcc_path' : save_path,
            'filepath'  : filepath
        })

    except Exception as e:
        failed.append({'filename': filename, 'error': str(e)})

print(f"\nSuccessfully extracted: {len(mfcc_records)}")
print(f"Failed                : {len(failed)}")
if failed:
    print("Failed files:", [f['filename'] for f in failed])

# Save MFCC index
mfcc_df = pd.DataFrame(mfcc_records)
mfcc_df.to_csv('data/mfcc_index.csv', index=False)
print("\nMFCC index saved.")
print(mfcc_df.head())

"""Verify MFCC shape and quality"""

# Load a sample MFCC and check
sample_path = mfcc_df['mfcc_path'].iloc[0]
sample      = np.load(sample_path)

print("MFCC vector shape   :", sample.shape)
print("First 10 values     :", sample[:10].round(3))
print("Min / Max           :", sample.min().round(3), "/", sample.max().round(3))

# Load all MFCCs into one matrix
print("\nLoading all MFCCs into memory...")
X_audio = np.array([np.load(p) for p in mfcc_df['mfcc_path']])
y_genre = mfcc_df['genre'].values

print("X_audio shape :", X_audio.shape)
print("Genres        :", np.unique(y_genre))

"""Extract mel-spectrograms (for Conv-VAE in medium task)"""

import librosa
from tqdm import tqdm

SPEC_DIR  = 'data/spectrograms'
N_MELS    = 128
HOP_LEN   = 512
TARGET_LEN = 128

spec_records = []

print(f"Extracting mel-spectrograms from {len(gtzan_df)} tracks...")

for idx, row in tqdm(gtzan_df.iterrows(), total=len(gtzan_df)):
    filepath = row['filepath']
    filename = row['filename']
    genre    = row['genre']

    try:
        y, sr = librosa.load(filepath, sr=SR, duration=DURATION)

        # Mel-spectrogram — shape (128, T)
        mel = librosa.feature.melspectrogram(
            y=y, sr=sr,
            n_mels=N_MELS,
            hop_length=HOP_LEN
        )

        # Convert to dB scale
        mel_db = librosa.power_to_db(mel, ref=np.max)

        # Fix time axis to TARGET_LEN (128) for consistent input shape
        if mel_db.shape[1] >= TARGET_LEN:
            mel_fixed = mel_db[:, :TARGET_LEN]
        else:
            # Pad with minimum value if shorter
            pad_width = TARGET_LEN - mel_db.shape[1]
            mel_fixed = np.pad(mel_db, ((0,0),(0,pad_width)), mode='minimum')

        # Final shape: (128, 128) — suitable for 2D Conv layers
        save_name = filename.replace('.au', '.npy')
        save_path = os.path.join(SPEC_DIR, save_name)
        np.save(save_path, mel_fixed)

        spec_records.append({
            'filename'  : filename,
            'genre'     : genre,
            'spec_path' : save_path,
            'shape'     : mel_fixed.shape
        })

    except Exception as e:
        print(f"Error on {filename}: {e}")

print(f"\nSuccessfully extracted: {len(spec_records)}")

spec_df = pd.DataFrame(spec_records)
spec_df.to_csv('data/spec_index.csv', index=False)
print("Spectrogram index saved.")


sample_spec = np.load(spec_df['spec_path'].iloc[0])
print("Sample spectrogram shape:", sample_spec.shape)

"""Generate lyrics embeddings"""

os.system('pip install -q sentence-transformers')

from sentence_transformers import SentenceTransformer
import numpy as np

print("Loading multilingual embedding model...")
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
print("Model loaded.")

# Prepare Hindi lyrics
hindi_texts  = df['hindi_lyrics_clean'].fillna('').tolist()
english_texts = df['english_lyrics_clean'].fillna('').tolist()

print(f"\nEncoding {len(hindi_texts)} Hindi lyrics...")
hindi_embeddings = model.encode(
    hindi_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print(f"\nEncoding {len(english_texts)} English translations...")
english_embeddings = model.encode(
    english_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("\nHindi embeddings shape  :", hindi_embeddings.shape)    # (4101, 384)
print("English embeddings shape:", english_embeddings.shape)   # (4101, 384)

# Save both
np.save('data/embeddings/hindi_embeddings.npy',   hindi_embeddings)
np.save('data/embeddings/english_embeddings.npy', english_embeddings)

# Also save a combined embedding (mean of Hindi + English per song)
combined_embeddings = (hindi_embeddings + english_embeddings) / 2.0
np.save('data/embeddings/combined_embeddings.npy', combined_embeddings)

print("\nAll embeddings saved.")
print("Combined embeddings shape:", combined_embeddings.shape)

"""Normalise MFCC features and create train/test split"""

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import joblib

# Normalise MFCC features
scaler   = StandardScaler()
X_scaled = scaler.fit_transform(X_audio)

print("X_scaled shape :", X_scaled.shape)
print("Mean (should be ~0)  :", X_scaled.mean().round(4))
print("Std  (should be ~1)  :", X_scaled.std().round(4))

# Save scaler
joblib.dump(scaler, 'data/mfcc_scaler.pkl')

# Train / test split — stratified by genre
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_genre,
    test_size=0.2,
    random_state=42,
    stratify=y_genre
)

np.save('data/X_train.npy', X_train)
np.save('data/X_test.npy',  X_test)
np.save('data/y_train.npy', y_train)
np.save('data/y_test.npy',  y_test)

print(f"\nTrain set : {X_train.shape}")
print(f"Test set  : {X_test.shape}")
print(f"\nGenre distribution in train:")
unique, counts = np.unique(y_train, return_counts=True)
for u, c in zip(unique, counts):
    print(f"  {u:12s}: {c}")

"""Save all extracted features to Drive"""

import shutil
import os

feat_save_dir = '/content/drive/MyDrive/VAE_Music_Project/features'
os.makedirs(feat_save_dir, exist_ok=True)

# ------------------------------------------------------------------
# 1. Create spectrogram folder in Drive
# ------------------------------------------------------------------
spec_save_dir = os.path.join(feat_save_dir, 'spectrograms')
os.makedirs(spec_save_dir, exist_ok=True)

# ------------------------------------------------------------------
# 2. Copy all spectrogram .npy files into Drive
# ------------------------------------------------------------------
print("Copying spectrogram files to Drive...")

spec_source_dir = 'data/spectrograms'
copied_specs = 0

for fname in os.listdir(spec_source_dir):
    if fname.endswith('.npy'):
        shutil.copy(
            os.path.join(spec_source_dir, fname),
            os.path.join(spec_save_dir, fname)
        )
        copied_specs += 1

print(f"Spectrogram files copied: {copied_specs}")

# ------------------------------------------------------------------
# 3. Rewrite spec_path so CSV points to Drive paths
# ------------------------------------------------------------------
spec_df['spec_path'] = spec_df['filename'].apply(
    lambda x: os.path.join(spec_save_dir, x.replace('.au', '.npy'))
)

# Save corrected index CSVs
mfcc_df.to_csv(f'{feat_save_dir}/mfcc_index.csv', index=False)
spec_df.to_csv(f'{feat_save_dir}/spec_index.csv', index=False)

# ------------------------------------------------------------------
# 4. Copy train/test arrays
# ------------------------------------------------------------------
for fname in ['X_train.npy', 'X_test.npy', 'y_train.npy', 'y_test.npy']:
    shutil.copy(f'data/{fname}', f'{feat_save_dir}/{fname}')

# ------------------------------------------------------------------
# 5. Copy embeddings
# ------------------------------------------------------------------
for fname in ['hindi_embeddings.npy', 'english_embeddings.npy', 'combined_embeddings.npy']:
    shutil.copy(
        f'data/embeddings/{fname}',
        f'{feat_save_dir}/{fname}'
    )

# ------------------------------------------------------------------
# 6. Copy scaler
# ------------------------------------------------------------------
shutil.copy('data/mfcc_scaler.pkl', f'{feat_save_dir}/mfcc_scaler.pkl')

# ------------------------------------------------------------------
# 7. Print summary
# ------------------------------------------------------------------
print("\nAll features saved to Drive:")
print(f"Location: {feat_save_dir}")

print("\nFiles saved:")
for f in os.listdir(feat_save_dir):
    full_path = os.path.join(feat_save_dir, f)

    if os.path.isfile(full_path):
        size = os.path.getsize(full_path) / 1024
        print(f"  {f:40s} {size:.1f} KB")

print(f"\nSpectrogram folder contains: {len(os.listdir(spec_save_dir))} files")
print("\nUpdated spec_index.csv now contains valid Drive paths.")

"""Final feature summary"""

print("=" * 55)
print("FEATURE EXTRACTION COMPLETE")
print("=" * 55)

X_train = np.load('data/X_train.npy')
X_test  = np.load('data/X_test.npy')
h_emb   = np.load('data/embeddings/hindi_embeddings.npy')
e_emb   = np.load('data/embeddings/english_embeddings.npy')
s_shape = np.load(spec_df['spec_path'].iloc[0]).shape

print(f"\nMFCC features (train)     : {X_train.shape}")
print(f"MFCC features (test)      : {X_test.shape}")
print(f"MFCC feature dimension    : {X_train.shape[1]}  (40 mean + 40 std)")
print(f"\nMel-spectrogram shape     : {s_shape}  (per track)")
print(f"\nHindi lyrics embeddings   : {h_emb.shape}")
print(f"English lyrics embeddings : {e_emb.shape}")
print(f"Embedding dimension       : {h_emb.shape[1]}")
print(f"\nReady for VAE training.")