# -*- coding: utf-8 -*-
"""feature_extraction_part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jO09PtpA42wSCUD64ZJHEOTtlX3i_shy

# Feature Extraction Part 2 — GTZAN Whisper Pseudo-Lyrics + Hindi Lyrics

This notebook rebuilds a clean metadata file and feature set after generating Whisper transcripts for GTZAN.

## Goal

Create a new metadata table with **1000 total samples**:

- **500 GTZAN songs** with Whisper-generated pseudo-lyrics
- **500 Hindi Bollywood songs** with cleaned Hindi lyrics

Required metadata columns:

`song_title, filename, filepath, genre_label, language, source, lyrics_text, has_audio, has_lyrics`

## Important note

GTZAN Whisper transcripts are **pseudo-lyrics**, not ground-truth lyrics. Some transcripts may be noisy or corrupted because GTZAN contains instrumental and mixed-audio tracks.

## 1. Mount Drive and install dependencies
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q librosa soundfile tqdm pandas numpy scikit-learn sentence-transformers joblib

"""## 2. Imports and paths"""

import os
import re
import zipfile
import shutil
import numpy as np
import pandas as pd
from tqdm import tqdm

PROJECT_DIR = "/content/drive/MyDrive/VAE_Music_Project"

DATA_DIR     = f"{PROJECT_DIR}/data"
FEATURE_DIR  = f"{PROJECT_DIR}/features"
RAW_DIR      = f"{PROJECT_DIR}/raw_data"
WHISPER_DIR  = f"{PROJECT_DIR}/gtzan_whisper_lyrics"

PART2_DIR = f"{PROJECT_DIR}/features_part2"
LOCAL_DIR = "/content/feature_extraction_part2"

os.makedirs(PART2_DIR, exist_ok=True)
os.makedirs(LOCAL_DIR, exist_ok=True)

LOCAL_AUDIO_DIR = "/content/data/audio"
os.makedirs(LOCAL_AUDIO_DIR, exist_ok=True)

print("PROJECT_DIR :", PROJECT_DIR)
print("DATA_DIR    :", DATA_DIR)
print("FEATURE_DIR :", FEATURE_DIR)
print("WHISPER_DIR :", WHISPER_DIR)
print("PART2_DIR   :", PART2_DIR)

import os

GTZAN_ZIP = "/content/drive/MyDrive/VAE_Music_Project/raw_data/gtzan.zip"
BOLLYWOOD_ZIP = "/content/drive/MyDrive/VAE_Music_Project/raw_data/bollywood.zip"
print(os.path.exists(GTZAN_ZIP))
print(os.path.exists(BOLLYWOOD_ZIP))

"""## 3. Helper functions"""

def find_first_existing(paths):
    for p in paths:
        if p and os.path.exists(p):
            return p
    return None


def clean_generated_lyrics(text):
    # Basic text cleaning for Whisper pseudo-lyrics.
    if pd.isna(text):
        return ""
    text = str(text)
    text = re.sub(r"\n+", " ", text)
    text = re.sub(r"\s+", " ", text)
    text = text.strip()
    return text


def word_count(text):
    text = clean_generated_lyrics(text)
    if not text:
        return 0
    return len(text.split())


def is_corrupted_or_low_quality(text, min_words=5, max_repetition_ratio=0.65):
    # Flags empty, too-short, or highly repetitive transcripts.
    text = clean_generated_lyrics(text)
    words = text.lower().split()

    if len(words) < min_words:
        return True

    unique_ratio = len(set(words)) / max(len(words), 1)
    repetition_ratio = 1 - unique_ratio

    if repetition_ratio > max_repetition_ratio:
        return True

    bad_phrases = [
        "thank you",
        "thanks for watching",
        "applause",
        "music",
        "instrumental"
    ]
    low_text = text.lower()
    if len(words) <= 8 and any(p in low_text for p in bad_phrases):
        return True

    return False


def make_safe_title_from_filename(filename):
    if pd.isna(filename):
        return None
    name = os.path.basename(str(filename))
    name = re.sub(r"\.(au|wav|mp3|flac)$", "", name, flags=re.IGNORECASE)
    return name


def ensure_columns(df, required_cols, name="dataframe"):
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"{name} is missing required columns: {missing}. Found columns: {df.columns.tolist()}")

"""## 4. Load GTZAN Whisper transcripts"""

# The notebook checks multiple possible transcript locations.
TRANSCRIPT_PATH = find_first_existing([
    f"{WHISPER_DIR}/gtzan_whisper_transcripts.csv",
    f"{WHISPER_DIR}/gtzan_whisper_usable_pseudo_lyrics.csv",
    "/content/gtzan_whisper_transcripts.csv",
])

if TRANSCRIPT_PATH is None:
    raise FileNotFoundError(
        "Could not find GTZAN Whisper transcript CSV. "
        "Expected it in gtzan_whisper_lyrics/gtzan_whisper_transcripts.csv "
        "or upload it to /content."
    )

gtzan_trans = pd.read_csv(TRANSCRIPT_PATH)

print("Loaded:", TRANSCRIPT_PATH)
print("Shape :", gtzan_trans.shape)
print("Columns:", gtzan_trans.columns.tolist())
gtzan_trans.head()

"""## 5. Filter GTZAN transcripts and select 500 usable songs"""

# Accept different possible column names
if "whisper_transcript" not in gtzan_trans.columns:
    possible = [c for c in gtzan_trans.columns if "transcript" in c.lower() or "lyrics" in c.lower()]
    if possible:
        gtzan_trans = gtzan_trans.rename(columns={possible[0]: "whisper_transcript"})
    else:
        raise ValueError("No transcript/lyrics column found in GTZAN transcript CSV.")

if "transcript_word_count" not in gtzan_trans.columns:
    gtzan_trans["transcript_word_count"] = gtzan_trans["whisper_transcript"].apply(word_count)

if "status" not in gtzan_trans.columns:
    gtzan_trans["status"] = "ok"

if "genre" not in gtzan_trans.columns:
    # fallback: infer genre from filename like blues.00000.au
    gtzan_trans["genre"] = gtzan_trans["filename"].astype(str).str.split(".").str[0]

gtzan_trans["lyrics_text"] = gtzan_trans["whisper_transcript"].apply(clean_generated_lyrics)
gtzan_trans["is_bad_transcript"] = gtzan_trans["lyrics_text"].apply(
    lambda x: is_corrupted_or_low_quality(x, min_words=5)
)

usable_gtzan = gtzan_trans[
    (gtzan_trans["status"].astype(str).str.startswith("ok")) &
    (~gtzan_trans["is_bad_transcript"])
].copy()

print("Total GTZAN transcript rows :", len(gtzan_trans))
print("Usable GTZAN transcripts    :", len(usable_gtzan))
print("Bad/corrupted transcripts   :", int(gtzan_trans["is_bad_transcript"].sum()))

print("\nUsable by genre:")
print(usable_gtzan["genre"].value_counts())

# Select 500 GTZAN songs.
# Prefer balanced sampling across genre if possible.

N_GTZAN = 500

if len(usable_gtzan) < N_GTZAN:
    print(f"WARNING: Only {len(usable_gtzan)} usable GTZAN transcripts found. Using all available.")
    gtzan_500 = usable_gtzan.copy()
else:
    # balanced-ish by genre
    per_genre = max(1, N_GTZAN // usable_gtzan["genre"].nunique())
    sampled_parts = []

    for genre, sub in usable_gtzan.groupby("genre"):
        take_n = min(per_genre, len(sub))
        sampled_parts.append(sub.sample(n=take_n, random_state=42))

    gtzan_500 = pd.concat(sampled_parts, ignore_index=True)

    # Fill remaining from the full usable pool, excluding already selected filenames
    if len(gtzan_500) < N_GTZAN:
        selected_files = set(gtzan_500["filename"].astype(str))
        remaining = usable_gtzan[~usable_gtzan["filename"].astype(str).isin(selected_files)]
        needed = N_GTZAN - len(gtzan_500)
        if len(remaining) >= needed:
            extra = remaining.sample(n=needed, random_state=42)
            gtzan_500 = pd.concat([gtzan_500, extra], ignore_index=True)

    # if overshot, trim
    gtzan_500 = gtzan_500.sample(n=min(N_GTZAN, len(gtzan_500)), random_state=42).reset_index(drop=True)

print("Selected GTZAN rows:", gtzan_500.shape)
print(gtzan_500["genre"].value_counts())

"""## 6. Rebuild / verify GTZAN audio file paths"""

# This section tries to recover GTZAN audio files if they are still available.
# If raw_data/gtzan.zip is gone, the notebook still creates metadata and lyrics embeddings,
# but audio MFCC/spectrogram extraction will be skipped.

GTZAN_ZIP = f"{RAW_DIR}/gtzan.zip"

if os.path.exists(GTZAN_ZIP):
    print("Found GTZAN zip. Extracting locally...")
    with zipfile.ZipFile(GTZAN_ZIP, "r") as z:
        z.extractall(LOCAL_AUDIO_DIR)
    print("Extracted to:", LOCAL_AUDIO_DIR)
else:
    print("GTZAN zip not found:", GTZAN_ZIP)
    print("Will try existing file paths from transcript CSV.")

# Build filename -> filepath map from local extracted audio if available
audio_map = {}
for root, dirs, files in os.walk(LOCAL_AUDIO_DIR):
    for f in files:
        if f.lower().endswith((".au", ".wav", ".mp3", ".flac")):
            audio_map[f] = os.path.join(root, f)

print("Local audio files found:", len(audio_map))

fixed_paths = []
for _, row in gtzan_500.iterrows():
    fname = str(row.get("filename", ""))
    old_path = row.get("filepath", None)

    if fname in audio_map:
        fixed_paths.append(audio_map[fname])
    elif isinstance(old_path, str) and os.path.exists(old_path):
        fixed_paths.append(old_path)
    else:
        fixed_paths.append(None)

gtzan_500["fixed_filepath"] = fixed_paths
gtzan_500["has_audio"] = gtzan_500["fixed_filepath"].apply(lambda x: isinstance(x, str) and os.path.exists(x))

print("GTZAN selected rows:", len(gtzan_500))
print("Rows with available audio:", int(gtzan_500["has_audio"].sum()))
print("Rows without audio:", int((~gtzan_500["has_audio"]).sum()))

gtzan_500[["filename", "genre", "fixed_filepath", "has_audio", "lyrics_text"]].head()

"""## 7. Load Bollywood cleaned Hindi dataset and select 500 songs"""

BOLLYWOOD_PATH = find_first_existing([
    f"{DATA_DIR}/bollywood_clean.csv",
    "/content/bollywood_clean.csv",
])

if BOLLYWOOD_PATH is None:
    raise FileNotFoundError(
        "Could not find bollywood_clean.csv. Expected it in /content/drive/MyDrive/VAE_Music_Project/data/"
    )

bolly = pd.read_csv(BOLLYWOOD_PATH)
print("Loaded:", BOLLYWOOD_PATH)
print("Shape :", bolly.shape)
print("Columns:", bolly.columns.tolist())
bolly.head()

# Identify Hindi lyrics column
if "hindi_lyrics_clean" not in bolly.columns:
    possible = [c for c in bolly.columns if "hindi" in c.lower() and ("clean" in c.lower() or "lyrics" in c.lower())]
    if possible:
        bolly = bolly.rename(columns={possible[0]: "hindi_lyrics_clean"})
    else:
        raise ValueError("Could not find Hindi lyrics column.")

if "song_title" not in bolly.columns:
    possible_title = [c for c in bolly.columns if "title" in c.lower() or "song" in c.lower()]
    if possible_title:
        bolly = bolly.rename(columns={possible_title[0]: "song_title"})
    else:
        bolly["song_title"] = ["hindi_song_" + str(i) for i in range(len(bolly))]

if "emotion_category" not in bolly.columns:
    # fallback pseudo-label if missing
    bolly["emotion_category"] = pd.qcut(
        np.arange(len(bolly)),
        q=5,
        labels=["very_sad", "sad", "neutral", "happy", "very_happy"]
    ).astype(str)

bolly["lyrics_text"] = bolly["hindi_lyrics_clean"].apply(clean_generated_lyrics)
bolly["word_count"] = bolly["lyrics_text"].apply(word_count)

usable_hindi = bolly[bolly["word_count"] >= 5].copy()

N_HINDI = 500
if len(usable_hindi) < N_HINDI:
    print(f"WARNING: Only {len(usable_hindi)} Hindi rows available. Using all.")
    hindi_500 = usable_hindi.copy()
else:
    hindi_500 = usable_hindi.sample(n=N_HINDI, random_state=42).reset_index(drop=True)

print("Selected Hindi rows:", hindi_500.shape)
print(hindi_500[["song_title", "emotion_category", "lyrics_text"]].head())

"""## 8. Create new 1000-row metadata file"""

# GTZAN metadata
gtzan_meta = pd.DataFrame({
    "song_title": gtzan_500["filename"].apply(make_safe_title_from_filename),
    "filename": gtzan_500["filename"].astype(str),
    "filepath": gtzan_500["fixed_filepath"],
    "genre_label": gtzan_500["genre"].astype(str),
    "language": "english",
    "source": "gtzan_whisper",
    "lyrics_text": gtzan_500["lyrics_text"].astype(str),
    "has_audio": gtzan_500["has_audio"].astype(bool),
    "has_lyrics": True
})

# Hindi metadata
hindi_meta = pd.DataFrame({
    "song_title": hindi_500["song_title"].astype(str),
    "filename": None,
    "filepath": None,
    "genre_label": hindi_500["emotion_category"].astype(str),
    "language": "hindi",
    "source": "bollywood",
    "lyrics_text": hindi_500["lyrics_text"].astype(str),
    "has_audio": False,
    "has_lyrics": True
})

metadata_part2 = pd.concat([gtzan_meta, hindi_meta], ignore_index=True)

# enforce exact column order
metadata_cols = [
    "song_title", "filename", "filepath", "genre_label",
    "language", "source", "lyrics_text", "has_audio", "has_lyrics"
]
metadata_part2 = metadata_part2[metadata_cols]

META_PATH = f"{PART2_DIR}/metadata_part2_gtzan500_hindi500.csv"
metadata_part2.to_csv(META_PATH, index=False)

print("Saved metadata:", META_PATH)
print("Metadata shape:", metadata_part2.shape)
print("\nLanguage counts:")
print(metadata_part2["language"].value_counts())
print("\nSource counts:")
print(metadata_part2["source"].value_counts())
print("\nAudio availability:")
print(metadata_part2["has_audio"].value_counts())
metadata_part2.head()

"""## 9. Generate lyrics embeddings for GTZAN pseudo-lyrics and Hindi lyrics"""

from sentence_transformers import SentenceTransformer

print("Loading multilingual embedding model...")
embed_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
print("Model loaded.")

gtzan_texts = gtzan_meta["lyrics_text"].fillna("").astype(str).tolist()
hindi_texts = hindi_meta["lyrics_text"].fillna("").astype(str).tolist()
all_texts   = metadata_part2["lyrics_text"].fillna("").astype(str).tolist()

print("Encoding GTZAN pseudo-lyrics:", len(gtzan_texts))
gtzan_lyrics_embeddings = embed_model.encode(
    gtzan_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Encoding Hindi lyrics:", len(hindi_texts))
hindi_embeddings = embed_model.encode(
    hindi_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Encoding all lyrics:", len(all_texts))
all_lyrics_embeddings = embed_model.encode(
    all_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

np.save(f"{PART2_DIR}/gtzan500_whisper_lyrics_embeddings.npy", gtzan_lyrics_embeddings)
np.save(f"{PART2_DIR}/hindi500_lyrics_embeddings.npy", hindi_embeddings)
np.save(f"{PART2_DIR}/all1000_lyrics_embeddings.npy", all_lyrics_embeddings)

print("GTZAN lyrics embeddings:", gtzan_lyrics_embeddings.shape)
print("Hindi lyrics embeddings:", hindi_embeddings.shape)
print("All lyrics embeddings:", all_lyrics_embeddings.shape)

"""## 10. Extract MFCC features for GTZAN rows with available audio"""

import librosa
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import joblib

MFCC_DIR = f"{PART2_DIR}/mfcc_gtzan500"
os.makedirs(MFCC_DIR, exist_ok=True)

N_MFCC = 40
SR = 22050
DURATION = 30

mfcc_records = []
failed_mfcc = []

audio_gtzan = gtzan_meta[gtzan_meta["has_audio"] == True].copy()

if len(audio_gtzan) == 0:
    print("WARNING: No GTZAN audio files are available. Skipping MFCC extraction.")
else:
    print("Extracting MFCC from available GTZAN audio files:", len(audio_gtzan))

    for idx, row in tqdm(audio_gtzan.iterrows(), total=len(audio_gtzan)):
        filepath = row["filepath"]
        filename = row["filename"]
        genre = row["genre_label"]

        try:
            y, sr = librosa.load(filepath, sr=SR, duration=DURATION)
            mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=N_MFCC)
            mfcc_mean = mfcc.mean(axis=1)
            mfcc_std = mfcc.std(axis=1)
            mfcc_combined = np.concatenate([mfcc_mean, mfcc_std]).astype(np.float32)

            save_name = filename.replace(".au", ".npy").replace(".wav", ".npy").replace(".mp3", ".npy")
            save_path = os.path.join(MFCC_DIR, save_name)
            np.save(save_path, mfcc_combined)

            mfcc_records.append({
                "filename": filename,
                "filepath": filepath,
                "genre": genre,
                "mfcc_path": save_path
            })
        except Exception as e:
            failed_mfcc.append({
                "filename": filename,
                "error": str(e)
            })

mfcc_df = pd.DataFrame(mfcc_records)
mfcc_index_path = f"{PART2_DIR}/mfcc_index_gtzan500.csv"
mfcc_df.to_csv(mfcc_index_path, index=False)

print("MFCC extracted:", len(mfcc_df))
print("MFCC failed:", len(failed_mfcc))
print("Saved MFCC index:", mfcc_index_path)

if len(mfcc_df) > 0:
    X_audio = np.array([np.load(p) for p in mfcc_df["mfcc_path"]])
    y_genre = mfcc_df["genre"].values

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_audio)

    np.save(f"{PART2_DIR}/X_gtzan500_mfcc_scaled.npy", X_scaled)
    np.save(f"{PART2_DIR}/y_gtzan500_genre.npy", y_genre)
    joblib.dump(scaler, f"{PART2_DIR}/mfcc_scaler_part2.pkl")

    genre_counts = pd.Series(y_genre).value_counts()
    can_stratify = genre_counts.min() >= 2

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled,
        y_genre,
        test_size=0.2,
        random_state=42,
        stratify=y_genre if can_stratify else None
    )

    np.save(f"{PART2_DIR}/X_train.npy", X_train)
    np.save(f"{PART2_DIR}/X_test.npy", X_test)
    np.save(f"{PART2_DIR}/y_train.npy", y_train)
    np.save(f"{PART2_DIR}/y_test.npy", y_test)

    print("X_audio:", X_audio.shape)
    print("X_train:", X_train.shape)
    print("X_test :", X_test.shape)

"""## 11. Extract mel-spectrograms for GTZAN rows with available audio"""

SPEC_DIR = f"{PART2_DIR}/spectrograms_gtzan500"
os.makedirs(SPEC_DIR, exist_ok=True)

N_MELS = 128
HOP_LEN = 512
TARGET_LEN = 128

spec_records = []
failed_spec = []

if len(audio_gtzan) == 0:
    print("WARNING: No GTZAN audio files are available. Skipping spectrogram extraction.")
else:
    print("Extracting mel-spectrograms:", len(audio_gtzan))

    for idx, row in tqdm(audio_gtzan.iterrows(), total=len(audio_gtzan)):
        filepath = row["filepath"]
        filename = row["filename"]
        genre = row["genre_label"]

        try:
            y, sr = librosa.load(filepath, sr=SR, duration=DURATION)

            mel = librosa.feature.melspectrogram(
                y=y,
                sr=sr,
                n_mels=N_MELS,
                hop_length=HOP_LEN
            )
            mel_db = librosa.power_to_db(mel, ref=np.max)

            if mel_db.shape[1] >= TARGET_LEN:
                mel_fixed = mel_db[:, :TARGET_LEN]
            else:
                pad_width = TARGET_LEN - mel_db.shape[1]
                mel_fixed = np.pad(
                    mel_db,
                    ((0, 0), (0, pad_width)),
                    mode="minimum"
                )

            mel_fixed = mel_fixed.astype(np.float32)

            save_name = filename.replace(".au", ".npy").replace(".wav", ".npy").replace(".mp3", ".npy")
            save_path = os.path.join(SPEC_DIR, save_name)
            np.save(save_path, mel_fixed)

            spec_records.append({
                "filename": filename,
                "filepath": filepath,
                "genre": genre,
                "spec_path": save_path,
                "shape": str(mel_fixed.shape)
            })
        except Exception as e:
            failed_spec.append({
                "filename": filename,
                "error": str(e)
            })

spec_df = pd.DataFrame(spec_records)
spec_index_path = f"{PART2_DIR}/spec_index_gtzan500.csv"
spec_df.to_csv(spec_index_path, index=False)

print("Spectrograms extracted:", len(spec_df))
print("Spectrograms failed:", len(failed_spec))
print("Saved spec index:", spec_index_path)

if len(spec_df) > 0:
    sample_spec = np.load(spec_df["spec_path"].iloc[0])
    print("Sample spectrogram shape:", sample_spec.shape)

"""## 12. Create task-ready feature matrices"""

labels_language = metadata_part2["language"].values
labels_source = metadata_part2["source"].values
labels_genre = metadata_part2["genre_label"].values

np.save(f"{PART2_DIR}/labels_language_1000.npy", labels_language)
np.save(f"{PART2_DIR}/labels_source_1000.npy", labels_source)
np.save(f"{PART2_DIR}/labels_genre_1000.npy", labels_genre)

print("Saved task-ready labels and feature matrices.")
print("Available files in PART2_DIR:")
for f in sorted(os.listdir(PART2_DIR)):
    p = os.path.join(PART2_DIR, f)
    if os.path.isfile(p):
        print(" -", f)

"""## 13. Final feature extraction summary"""

print("=" * 55)
print("FEATURE EXTRACTION PART 2 COMPLETE")
print("=" * 55)

print(f"\nMetadata file              : {META_PATH}")
print(f"Metadata shape             : {metadata_part2.shape}")
print(f"GTZAN rows                 : {(metadata_part2['source'] == 'gtzan_whisper').sum()}")
print(f"Hindi rows                 : {(metadata_part2['source'] == 'bollywood').sum()}")

print(f"\nGTZAN lyrics embeddings    : {gtzan_lyrics_embeddings.shape}")
print(f"Hindi lyrics embeddings    : {hindi_embeddings.shape}")
print(f"All lyrics embeddings      : {all_lyrics_embeddings.shape}")
print(f"Embedding dimension        : {all_lyrics_embeddings.shape[1]}")

if 'X_train' in globals():
    print(f"\nMFCC features (train)      : {X_train.shape}")
    print(f"MFCC features (test)       : {X_test.shape}")
    print(f"MFCC feature dimension     : {X_train.shape[1]}  (40 mean + 40 std)")
else:
    print("\nMFCC features              : SKIPPED because GTZAN audio files were not available.")

if len(spec_df) > 0:
    s_shape = np.load(spec_df['spec_path'].iloc[0]).shape
    print(f"\nMel-spectrogram shape      : {s_shape}  (per GTZAN track)")
else:
    print("\nMel-spectrograms           : SKIPPED because GTZAN audio files were not available.")

print(f"\nSaved everything to        : {PART2_DIR}")
print("\nReady for VAE training.")

"""## 14. How to use these outputs

### For Easy Task
Use GTZAN MFCC if available:

- `X_train.npy`
- `X_test.npy`
- `y_train.npy`
- `y_test.npy`

### For Medium Task
Use:

- GTZAN spectrograms from `spec_index_gtzan500.csv`
- GTZAN pseudo-lyrics embeddings from `gtzan500_whisper_lyrics_embeddings.npy`

### For Hard Task
Use:

- GTZAN audio latent features from MFCC/spectrograms
- GTZAN pseudo-lyrics embeddings
- `genre_label` as label/condition
- Hindi lyrics embeddings for language-level analysis

### Important report note
Whisper transcripts are pseudo-lyrics and may be noisy. Mention that short/corrupted transcripts were filtered before feature extraction.

"""