# -*- coding: utf-8 -*-
"""hard_task_with_837.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DUCE5p-lgkTTrNr1272UKmkCuJSSHWYh

# Hard Task — Beta-VAE / CVAE Multimodal Music Clustering

This notebook implements the **Hard Task** using the current `features_part2` dataset.

## Dataset used

Main hard-task subset:

- GTZAN paired samples
- Audio: MFCC features and mel-spectrograms
- Lyrics: Whisper-generated pseudo-lyrics embeddings
- Genre: GTZAN genre label used as clustering label and CVAE conditioning variable

## Requirements covered

1. Beta-VAE and CVAE for disentangled / conditional latent representation learning
2. Multimodal clustering using audio, lyrics, and genre information
3. Metrics: Silhouette, NMI, ARI, Cluster Purity, Davies-Bouldin, Calinski-Harabasz
4. Visualizations: t-SNE, UMAP, cluster distribution, reconstruction examples
5. Baselines: PCA + K-Means, Autoencoder + K-Means, direct spectral feature clustering
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q umap-learn pandas numpy scikit-learn matplotlib torch

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import (
    silhouette_score,
    normalized_mutual_info_score,
    adjusted_rand_score,
    davies_bouldin_score,
    calinski_harabasz_score,
)
from sklearn.manifold import TSNE
import umap

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

PROJECT_DIR = "/content/drive/MyDrive/VAE_Music_Project"
PART2_DIR = f"{PROJECT_DIR}/features_part2"
RESULTS_DIR = f"{PROJECT_DIR}/results/hard_task_part2"

os.makedirs(RESULTS_DIR, exist_ok=True)

print("PART2_DIR:", PART2_DIR)
print("RESULTS_DIR:", RESULTS_DIR)

META_PATH = f"{PART2_DIR}/metadata_part2_gtzan500_hindi500.csv"
MFCC_INDEX_PATH = f"{PART2_DIR}/mfcc_index_gtzan500.csv"
SPEC_INDEX_PATH = f"{PART2_DIR}/spec_index_gtzan500.csv"
GTZAN_TEXT_EMB_PATH = f"{PART2_DIR}/gtzan500_whisper_lyrics_embeddings.npy"

for p in [META_PATH, MFCC_INDEX_PATH, SPEC_INDEX_PATH, GTZAN_TEXT_EMB_PATH]:
    print(p, "exists:", os.path.exists(p))

metadata = pd.read_csv(META_PATH)
mfcc_df = pd.read_csv(MFCC_INDEX_PATH)
spec_df = pd.read_csv(SPEC_INDEX_PATH)
gtzan_text_emb = np.load(GTZAN_TEXT_EMB_PATH)

print("\nMetadata:", metadata.shape)
print("MFCC index:", mfcc_df.shape)
print("Spec index:", spec_df.shape)
print("GTZAN text embeddings:", gtzan_text_emb.shape)

gtzan_meta = metadata[metadata["source"] == "gtzan_whisper"].copy().reset_index(drop=True)
gtzan_meta["gtzan_order"] = np.arange(len(gtzan_meta))

if len(gtzan_meta) != len(gtzan_text_emb):
    raise ValueError(
        f"Mismatch: gtzan_meta rows = {len(gtzan_meta)}, text embeddings = {len(gtzan_text_emb)}"
    )

paired = mfcc_df.merge(spec_df[["filename", "spec_path"]], on="filename", how="inner")
paired = paired.merge(
    gtzan_meta[["filename", "genre_label", "lyrics_text", "language", "source", "gtzan_order"]],
    on="filename",
    how="inner"
).reset_index(drop=True)

print("Paired rows before file check:", paired.shape)
display(paired.head())

mfcc_list = []
specs = []
valid_rows = []

for i, row in paired.iterrows():
    mfcc_path = row["mfcc_path"]
    spec_path = row["spec_path"]
    if not (isinstance(mfcc_path, str) and os.path.exists(mfcc_path)):
        continue
    if not (isinstance(spec_path, str) and os.path.exists(spec_path)):
        continue

    try:
        mfcc = np.load(mfcc_path).astype(np.float32)
        spec = np.load(spec_path).astype(np.float32)
        if spec.ndim == 3:
            spec = spec[0]
        if spec.shape != (128, 128):
            fixed = np.zeros((128, 128), dtype=np.float32)
            h = min(128, spec.shape[0])
            w = min(128, spec.shape[1])
            fixed[:h, :w] = spec[:h, :w]
            spec = fixed

        mfcc_list.append(mfcc)
        specs.append(spec)
        valid_rows.append(i)
    except Exception:
        continue

paired = paired.iloc[valid_rows].reset_index(drop=True)

X_mfcc_raw = np.stack(mfcc_list).astype(np.float32)
X_spec = np.stack(specs).astype(np.float32)[:, np.newaxis, :, :]

text_indices = paired["gtzan_order"].values
X_text_raw = gtzan_text_emb[text_indices].astype(np.float32)

spec_min = X_spec.min()
spec_max = X_spec.max()
X_spec = 2.0 * (X_spec - spec_min) / (spec_max - spec_min + 1e-8) - 1.0
X_spec = X_spec.astype(np.float32)

y_genre = paired["genre_label"].astype(str).values
y_language = paired["language"].astype(str).values

le_genre = LabelEncoder()
y_genre_enc = le_genre.fit_transform(y_genre)

N_CLASSES = len(le_genre.classes_)
C_genre = np.eye(N_CLASSES, dtype=np.float32)[y_genre_enc]

print("Final paired samples:", len(paired))
print("X_mfcc_raw:", X_mfcc_raw.shape)
print("X_text_raw:", X_text_raw.shape)
print("X_spec:", X_spec.shape)
print("Genres:", list(le_genre.classes_))
print(pd.Series(y_genre).value_counts())

mfcc_scaler = StandardScaler()
X_mfcc = mfcc_scaler.fit_transform(X_mfcc_raw).astype(np.float32)

text_scaler = StandardScaler()
X_text = text_scaler.fit_transform(X_text_raw).astype(np.float32)

print("MFCC normalized:", X_mfcc.shape)
print("Text normalized:", X_text.shape)
print("Condition matrix:", C_genre.shape)

class FCEncoder(nn.Module):
    def __init__(self, input_dim, hidden_dims, latent_dim):
        super().__init__()
        layers = []
        prev = input_dim
        for h in hidden_dims:
            layers += [nn.Linear(prev, h), nn.BatchNorm1d(h), nn.LeakyReLU(0.2)]
            prev = h
        self.net = nn.Sequential(*layers)
        self.mu = nn.Linear(prev, latent_dim)
        self.logv = nn.Linear(prev, latent_dim)

    def forward(self, x):
        h = self.net(x)
        return self.mu(h), self.logv(h)


class FCDecoder(nn.Module):
    def __init__(self, latent_dim, hidden_dims, output_dim):
        super().__init__()
        layers = []
        prev = latent_dim
        for h in reversed(hidden_dims):
            layers += [nn.Linear(prev, h), nn.BatchNorm1d(h), nn.LeakyReLU(0.2)]
            prev = h
        layers.append(nn.Linear(prev, output_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, z):
        return self.net(z)


class BetaVAE(nn.Module):
    def __init__(self, input_dim=80, hidden_dims=(256, 128), latent_dim=32, beta=4.0):
        super().__init__()
        self.encoder = FCEncoder(input_dim, hidden_dims, latent_dim)
        self.decoder = FCDecoder(latent_dim, hidden_dims, input_dim)
        self.beta = beta

    def reparameterize(self, mu, logv):
        return mu + torch.randn_like(mu) * torch.exp(0.5 * logv)

    def forward(self, x):
        mu, logv = self.encoder(x)
        z = self.reparameterize(mu, logv)
        xr = self.decoder(z)
        return xr, mu, logv

    def encode(self, x):
        return self.encoder(x)[0]

    def loss(self, x, xr, mu, logv):
        recon = F.mse_loss(xr, x, reduction="mean")
        kl = -0.5 * torch.mean(1 + logv - mu.pow(2) - logv.exp())
        return recon + self.beta * kl, recon, kl


class CVAE(nn.Module):
    def __init__(self, input_dim=80, cond_dim=4, hidden_dims=(256, 128), latent_dim=32):
        super().__init__()
        self.cond_proj = nn.Sequential(nn.Linear(cond_dim, 32), nn.LeakyReLU(0.2))
        self.encoder = FCEncoder(input_dim + 32, hidden_dims, latent_dim)
        self.decoder = FCDecoder(latent_dim + 32, hidden_dims, input_dim)

    def reparameterize(self, mu, logv):
        return mu + torch.randn_like(mu) * torch.exp(0.5 * logv)

    def encode_dist(self, x, c):
        cp = self.cond_proj(c)
        return self.encoder(torch.cat([x, cp], dim=1))

    def get_latent(self, x, c):
        return self.encode_dist(x, c)[0]

    def decode(self, z, c):
        cp = self.cond_proj(c)
        return self.decoder(torch.cat([z, cp], dim=1))

    def forward(self, x, c):
        mu, logv = self.encode_dist(x, c)
        z = self.reparameterize(mu, logv)
        xr = self.decode(z, c)
        return xr, mu, logv

    def loss(self, x, xr, mu, logv, beta=1.0):
        recon = F.mse_loss(xr, x, reduction="mean")
        kl = -0.5 * torch.mean(1 + logv - mu.pow(2) - logv.exp())
        return recon + beta * kl, recon, kl


class Autoencoder(nn.Module):
    def __init__(self, input_dim=80, hidden_dims=(256, 128), latent_dim=32):
        super().__init__()
        enc_layers = []
        prev = input_dim
        for h in hidden_dims:
            enc_layers += [nn.Linear(prev, h), nn.BatchNorm1d(h), nn.LeakyReLU(0.2)]
            prev = h
        enc_layers.append(nn.Linear(prev, latent_dim))
        self.encoder = nn.Sequential(*enc_layers)

        dec_layers = []
        prev = latent_dim
        for h in reversed(hidden_dims):
            dec_layers += [nn.Linear(prev, h), nn.BatchNorm1d(h), nn.LeakyReLU(0.2)]
            prev = h
        dec_layers.append(nn.Linear(prev, input_dim))
        self.decoder = nn.Sequential(*dec_layers)

    def forward(self, x):
        z = self.encoder(x)
        return self.decoder(z), z

    def encode(self, x):
        return self.encoder(x)


class LyricsVAE(nn.Module):
    def __init__(self, input_dim=384, hidden_dims=(256, 128), latent_dim=32):
        super().__init__()
        self.encoder = FCEncoder(input_dim, hidden_dims, latent_dim)
        self.decoder = FCDecoder(latent_dim, hidden_dims, input_dim)

    def reparameterize(self, mu, logv):
        return mu + torch.randn_like(mu) * torch.exp(0.5 * logv)

    def forward(self, x):
        mu, logv = self.encoder(x)
        z = self.reparameterize(mu, logv)
        return self.decoder(z), mu, logv

    def encode(self, x):
        return self.encoder(x)[0]

    def loss(self, x, xr, mu, logv, beta=1.0):
        recon = F.mse_loss(xr, x, reduction="mean")
        kl = -0.5 * torch.mean(1 + logv - mu.pow(2) - logv.exp())
        return recon + beta * kl, recon, kl

def train_beta_vae(model, X, epochs=100, batch_size=64, lr=1e-3, tag="VAE"):
    ds = TensorDataset(torch.tensor(X, dtype=torch.float32))
    loader = DataLoader(ds, batch_size=batch_size, shuffle=True)
    opt = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    hist = {"loss": [], "recon": [], "kl": []}

    model.train()
    for epoch in range(1, epochs + 1):
        ep_loss = ep_recon = ep_kl = 0.0
        for (xb,) in loader:
            xb = xb.to(device)
            opt.zero_grad()
            xr, mu, logv = model(xb)
            loss, recon, kl = model.loss(xb, xr, mu, logv)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            ep_loss += loss.item()
            ep_recon += recon.item()
            ep_kl += kl.item()

        n = len(loader)
        hist["loss"].append(ep_loss / n)
        hist["recon"].append(ep_recon / n)
        hist["kl"].append(ep_kl / n)
        if epoch == 1 or epoch % 20 == 0:
            print(f"[{tag}] epoch {epoch:03d}/{epochs} | loss={hist['loss'][-1]:.4f} | recon={hist['recon'][-1]:.4f} | kl={hist['kl'][-1]:.4f}")
    model.eval()
    return hist


def train_cvae(model, X, C, epochs=100, batch_size=64, lr=1e-3, beta=1.0):
    ds = TensorDataset(torch.tensor(X, dtype=torch.float32), torch.tensor(C, dtype=torch.float32))
    loader = DataLoader(ds, batch_size=batch_size, shuffle=True)
    opt = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    hist = {"loss": [], "recon": [], "kl": []}

    model.train()
    for epoch in range(1, epochs + 1):
        ep_loss = ep_recon = ep_kl = 0.0
        for xb, cb in loader:
            xb = xb.to(device)
            cb = cb.to(device)
            opt.zero_grad()
            xr, mu, logv = model(xb, cb)
            loss, recon, kl = model.loss(xb, xr, mu, logv, beta=beta)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            ep_loss += loss.item()
            ep_recon += recon.item()
            ep_kl += kl.item()

        n = len(loader)
        hist["loss"].append(ep_loss / n)
        hist["recon"].append(ep_recon / n)
        hist["kl"].append(ep_kl / n)
        if epoch == 1 or epoch % 20 == 0:
            print(f"[CVAE] epoch {epoch:03d}/{epochs} | loss={hist['loss'][-1]:.4f} | recon={hist['recon'][-1]:.4f} | kl={hist['kl'][-1]:.4f}")
    model.eval()
    return hist


def train_autoencoder(model, X, epochs=100, batch_size=64, lr=1e-3):
    ds = TensorDataset(torch.tensor(X, dtype=torch.float32))
    loader = DataLoader(ds, batch_size=batch_size, shuffle=True)
    opt = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    hist = {"loss": []}

    model.train()
    for epoch in range(1, epochs + 1):
        ep_loss = 0.0
        for (xb,) in loader:
            xb = xb.to(device)
            opt.zero_grad()
            xr, _ = model(xb)
            loss = F.mse_loss(xr, xb, reduction="mean")
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            ep_loss += loss.item()

        hist["loss"].append(ep_loss / len(loader))
        if epoch == 1 or epoch % 20 == 0:
            print(f"[AE] epoch {epoch:03d}/{epochs} | loss={hist['loss'][-1]:.4f}")
    model.eval()
    return hist

INPUT_DIM = X_mfcc.shape[1]
TEXT_DIM = X_text.shape[1]
LATENT_DIM = 32
HIDDEN = (256, 128)

EPOCHS = 100
BATCH_SIZE = 64
LR = 1e-3

beta_vae = BetaVAE(INPUT_DIM, HIDDEN, LATENT_DIM, beta=4.0).to(device)
cvae = CVAE(INPUT_DIM, N_CLASSES, HIDDEN, LATENT_DIM).to(device)
ae = Autoencoder(INPUT_DIM, HIDDEN, LATENT_DIM).to(device)
lyrics_vae = LyricsVAE(TEXT_DIM, HIDDEN, LATENT_DIM).to(device)

print("Training Beta-VAE...")
hist_beta = train_beta_vae(beta_vae, X_mfcc, EPOCHS, BATCH_SIZE, LR, "Beta-VAE")

print("\nTraining CVAE...")
hist_cvae = train_cvae(cvae, X_mfcc, C_genre, EPOCHS, BATCH_SIZE, LR, beta=1.0)

print("\nTraining Autoencoder baseline...")
hist_ae = train_autoencoder(ae, X_mfcc, EPOCHS, BATCH_SIZE, LR)

print("\nTraining Lyrics VAE...")
hist_lyrics = train_beta_vae(lyrics_vae, X_text, EPOCHS, BATCH_SIZE, LR, "Lyrics-VAE")

plt.figure(figsize=(10, 5))
plt.plot(hist_beta["loss"], label="Beta-VAE total")
plt.plot(hist_cvae["loss"], label="CVAE total")
plt.plot(hist_ae["loss"], label="Autoencoder")
plt.plot(hist_lyrics["loss"], label="Lyrics VAE total")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Hard Task Training Curves")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()

curve_path = f"{RESULTS_DIR}/hard_task_training_curves.png"
plt.savefig(curve_path, dpi=150, bbox_inches="tight")
plt.show()

with torch.no_grad():
    X_mfcc_t = torch.tensor(X_mfcc, dtype=torch.float32).to(device)
    X_text_t = torch.tensor(X_text, dtype=torch.float32).to(device)
    C_t = torch.tensor(C_genre, dtype=torch.float32).to(device)

    Z_beta = beta_vae.encode(X_mfcc_t).cpu().numpy()
    Z_cvae = cvae.get_latent(X_mfcc_t, C_t).cpu().numpy()
    Z_ae = ae.encode(X_mfcc_t).cpu().numpy()
    Z_lyrics = lyrics_vae.encode(X_text_t).cpu().numpy()

Z_beta_s = StandardScaler().fit_transform(Z_beta)
Z_cvae_s = StandardScaler().fit_transform(Z_cvae)
Z_ae_s = StandardScaler().fit_transform(Z_ae)
Z_lyrics_s = StandardScaler().fit_transform(Z_lyrics)

Z_fused_beta = np.concatenate([Z_beta_s, Z_lyrics_s], axis=1)
Z_fused_cvae = np.concatenate([Z_cvae_s, Z_lyrics_s], axis=1)

np.save(f"{RESULTS_DIR}/Z_beta.npy", Z_beta_s)
np.save(f"{RESULTS_DIR}/Z_cvae.npy", Z_cvae_s)
np.save(f"{RESULTS_DIR}/Z_lyrics.npy", Z_lyrics_s)
np.save(f"{RESULTS_DIR}/Z_fused_beta.npy", Z_fused_beta)
np.save(f"{RESULTS_DIR}/Z_fused_cvae.npy", Z_fused_cvae)

torch.save(beta_vae.state_dict(), f"{RESULTS_DIR}/beta_vae_audio.pth")
torch.save(cvae.state_dict(), f"{RESULTS_DIR}/cvae_audio_genre_conditioned.pth")
torch.save(ae.state_dict(), f"{RESULTS_DIR}/autoencoder_audio.pth")
torch.save(lyrics_vae.state_dict(), f"{RESULTS_DIR}/lyrics_vae.pth")

print("Z_beta:", Z_beta_s.shape)
print("Z_cvae:", Z_cvae_s.shape)
print("Z_lyrics:", Z_lyrics_s.shape)
print("Z_fused_beta:", Z_fused_beta.shape)
print("Z_fused_cvae:", Z_fused_cvae.shape)

def cluster_purity(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    total = 0
    for c in np.unique(y_pred):
        if c == -1:
            continue
        mask = y_pred == c
        if mask.sum() == 0:
            continue
        counts = np.bincount(y_true[mask])
        total += counts.max()
    return total / len(y_true)


def evaluate_kmeans(X, y_true, method_name, k):
    km = KMeans(n_clusters=k, random_state=SEED, n_init=20)
    pred = km.fit_predict(X)
    row = {
        "method": method_name,
        "n_clusters": k,
        "silhouette": silhouette_score(X, pred),
        "davies_bouldin": davies_bouldin_score(X, pred),
        "calinski_harabasz": calinski_harabasz_score(X, pred),
        "nmi": normalized_mutual_info_score(y_true, pred),
        "ari": adjusted_rand_score(y_true, pred),
        "purity": cluster_purity(y_true, pred),
    }
    return row, pred

K = N_CLASSES

pca_mfcc = PCA(n_components=LATENT_DIM, random_state=SEED)
Z_pca_mfcc = pca_mfcc.fit_transform(X_mfcc)

X_spec_flat = X_spec.reshape(X_spec.shape[0], -1)
pca_spec = PCA(n_components=LATENT_DIM, random_state=SEED)
Z_pca_spec = pca_spec.fit_transform(X_spec_flat)

print("Z_pca_mfcc:", Z_pca_mfcc.shape, "variance:", pca_mfcc.explained_variance_ratio_.sum())
print("Z_pca_spec:", Z_pca_spec.shape, "variance:", pca_spec.explained_variance_ratio_.sum())

results = []
cluster_assignments = {}

experiments = {
    "Beta-VAE audio latent + KMeans": Z_beta_s,
    "CVAE audio latent + KMeans": Z_cvae_s,
    "Fused Beta-VAE audio+lyrics latent + KMeans": Z_fused_beta,
    "Fused CVAE audio+lyrics latent + KMeans": Z_fused_cvae,
    "Autoencoder audio latent + KMeans": Z_ae_s,
    "PCA MFCC + KMeans": Z_pca_mfcc,
    "Direct spectral PCA + KMeans": Z_pca_spec,
}

for name, Z in experiments.items():
    row, pred = evaluate_kmeans(Z, y_genre_enc, name, K)
    results.append(row)
    cluster_assignments[name] = pred

metrics_df = pd.DataFrame(results)
metrics_path = f"{RESULTS_DIR}/hard_task_metrics.csv"
metrics_df.to_csv(metrics_path, index=False)

metrics_df

plot_df = metrics_df.copy()

for metric in ["silhouette", "nmi", "ari", "purity"]:
    plt.figure(figsize=(12, 5))
    plt.bar(plot_df["method"], plot_df[metric])
    plt.xticks(rotation=75, ha="right")
    plt.ylabel(metric.upper())
    plt.title(f"Hard Task Clustering Comparison — {metric.upper()}")
    plt.tight_layout()
    save_path = f"{RESULTS_DIR}/{metric}_comparison.png"
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    print("Saved:", save_path)

best_row = metrics_df.sort_values("nmi", ascending=False).iloc[0]
best_method = best_row["method"]
best_Z = experiments[best_method]
best_pred = cluster_assignments[best_method]

print("Best method by NMI:", best_method)
display(best_row)

perplexity_value = min(30, max(5, len(best_Z)//10))

tsne = TSNE(
    n_components=2,
    random_state=SEED,
    perplexity=perplexity_value,
    init="pca",
    learning_rate="auto"
)
Z_tsne = tsne.fit_transform(best_Z)

plt.figure(figsize=(9, 7))
for genre in sorted(np.unique(y_genre)):
    mask = y_genre == genre
    plt.scatter(Z_tsne[mask, 0], Z_tsne[mask, 1], s=25, alpha=0.75, label=genre)

plt.title(f"t-SNE Latent Space by Genre\n{best_method}")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.grid(alpha=0.25)
plt.tight_layout()

tsne_path = f"{RESULTS_DIR}/tsne_best_by_genre.png"
plt.savefig(tsne_path, dpi=150, bbox_inches="tight")
plt.show()

umap_model = umap.UMAP(n_components=2, random_state=SEED, n_neighbors=15, min_dist=0.1)
Z_umap = umap_model.fit_transform(best_Z)

plt.figure(figsize=(9, 7))
for genre in sorted(np.unique(y_genre)):
    mask = y_genre == genre
    plt.scatter(Z_umap[mask, 0], Z_umap[mask, 1], s=25, alpha=0.75, label=genre)

plt.title(f"UMAP Latent Space by Genre\n{best_method}")
plt.xlabel("UMAP 1")
plt.ylabel("UMAP 2")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.grid(alpha=0.25)
plt.tight_layout()

umap_path = f"{RESULTS_DIR}/umap_best_by_genre.png"
plt.savefig(umap_path, dpi=150, bbox_inches="tight")
plt.show()

cluster_df = pd.DataFrame({
    "cluster": best_pred,
    "genre": y_genre,
    "language": y_language
})

cluster_genre = pd.crosstab(cluster_df["cluster"], cluster_df["genre"])
cluster_language = pd.crosstab(cluster_df["cluster"], cluster_df["language"])

cluster_genre.to_csv(f"{RESULTS_DIR}/cluster_genre_distribution.csv")
cluster_language.to_csv(f"{RESULTS_DIR}/cluster_language_distribution.csv")

display(cluster_genre)
display(cluster_language)

cluster_genre_norm = cluster_genre.div(cluster_genre.sum(axis=1), axis=0)

cluster_genre_norm.plot(kind="bar", stacked=True, figsize=(10, 5))
plt.title(f"Cluster Distribution over Genres\n{best_method}")
plt.xlabel("Cluster")
plt.ylabel("Proportion")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()

cluster_plot_path = f"{RESULTS_DIR}/cluster_genre_distribution.png"
plt.savefig(cluster_plot_path, dpi=150, bbox_inches="tight")
plt.show()

n_examples = min(5, len(X_mfcc))
idxs = np.linspace(0, len(X_mfcc) - 1, n_examples, dtype=int)

beta_vae.eval()
cvae.eval()

with torch.no_grad():
    xb = torch.tensor(X_mfcc[idxs], dtype=torch.float32).to(device)
    cb = torch.tensor(C_genre[idxs], dtype=torch.float32).to(device)
    xr_beta, _, _ = beta_vae(xb)
    xr_cvae, _, _ = cvae(xb, cb)
    xr_beta = xr_beta.cpu().numpy()
    xr_cvae = xr_cvae.cpu().numpy()

fig, axes = plt.subplots(n_examples, 3, figsize=(12, 3 * n_examples))

for j, idx in enumerate(idxs):
    axes[j, 0].plot(X_mfcc[idx])
    axes[j, 0].set_title(f"Original MFCC\n{y_genre[idx]}")
    axes[j, 1].plot(xr_beta[j])
    axes[j, 1].set_title("Beta-VAE Reconstruction")
    axes[j, 2].plot(xr_cvae[j])
    axes[j, 2].set_title("CVAE Reconstruction")
    for k in range(3):
        axes[j, k].grid(alpha=0.3)

plt.suptitle("MFCC Reconstruction Examples from VAE Latent Space")
plt.tight_layout()

recon_path = f"{RESULTS_DIR}/mfcc_reconstruction_examples.png"
plt.savefig(recon_path, dpi=150, bbox_inches="tight")
plt.show()

print("=" * 70)
print("HARD TASK COMPLETE — SUMMARY")
print("=" * 70)

print(f'''
Dataset
  Paired GTZAN multimodal samples : {len(X_mfcc):,}
  Audio features                  : MFCC 80D + spectrogram 1x128x128
  Lyrics features                 : Whisper pseudo-lyrics embeddings 384D
  Genre labels / condition dim    : {N_CLASSES}
  Genres                          : {list(le_genre.classes_)}

Models
  Beta-VAE audio latent           : 32D
  CVAE audio latent               : 32D, conditioned on genre one-hot
  Lyrics VAE latent               : 32D
  Fused Beta-VAE audio+lyrics     : 64D
  Fused CVAE audio+lyrics         : 64D
  Autoencoder baseline            : 32D
  PCA MFCC baseline               : 32D
  Direct spectral PCA baseline    : 32D

Best method by NMI:
  {best_method}

Outputs saved to:
  {RESULTS_DIR}
''')

display(metrics_df.sort_values("nmi", ascending=False))