# -*- coding: utf-8 -*-
"""medium_task_with_837.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKBZAB6CvjBWpcf0Ik_3ypzKIgbYUEuX

# Medium Task — Conv-VAE + Hybrid Audio/Text Clustering

This notebook implements the **Medium Task** using the current `features_part2` dataset.

## Dataset used

This Medium Task focuses on the GTZAN subset that has both:

- Audio features: mel-spectrograms extracted from GTZAN audio
- Text features: Whisper-generated pseudo-lyrics embeddings for the same GTZAN tracks



## Medium Task requirements covered

1. Convolutional VAE for spectrogram-based audio representation learning
2. Hybrid feature representation using audio latent features + lyrics embeddings
3. Clustering algorithms:
   - K-Means
   - Agglomerative Clustering
   - DBSCAN
4. Evaluation metrics:
   - Silhouette Score
   - Davies-Bouldin Index
   - Adjusted Rand Index (ARI) using GTZAN genre labels
5. Comparison across representations and clustering methods

## 1. Mount Drive and install dependencies
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q umap-learn pandas numpy scikit-learn matplotlib torch

"""## 2. Imports and paths"""

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score, adjusted_rand_score, calinski_harabasz_score
from sklearn.neighbors import NearestNeighbors
from sklearn.manifold import TSNE
import umap

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

PROJECT_DIR = "/content/drive/MyDrive/VAE_Music_Project"
PART2_DIR = f"{PROJECT_DIR}/features_part2"
RESULTS_DIR = f"{PROJECT_DIR}/results/medium_task_part2"

os.makedirs(RESULTS_DIR, exist_ok=True)

print("PART2_DIR:", PART2_DIR)
print("RESULTS_DIR:", RESULTS_DIR)

"""## 3. Load metadata, spectrogram index, and GTZAN pseudo-lyrics embeddings"""

META_PATH = f"{PART2_DIR}/metadata_part2_gtzan500_hindi500.csv"
SPEC_INDEX_PATH = f"{PART2_DIR}/spec_index_gtzan500.csv"
GTZAN_TEXT_EMB_PATH = f"{PART2_DIR}/gtzan500_whisper_lyrics_embeddings.npy"

if not os.path.exists(META_PATH):
    raise FileNotFoundError(f"Metadata file not found: {META_PATH}")

if not os.path.exists(SPEC_INDEX_PATH):
    raise FileNotFoundError(f"Spectrogram index not found: {SPEC_INDEX_PATH}")

if not os.path.exists(GTZAN_TEXT_EMB_PATH):
    raise FileNotFoundError(f"GTZAN lyrics embeddings not found: {GTZAN_TEXT_EMB_PATH}")

metadata = pd.read_csv(META_PATH)
spec_df = pd.read_csv(SPEC_INDEX_PATH)
gtzan_text_emb = np.load(GTZAN_TEXT_EMB_PATH)

print("Metadata shape:", metadata.shape)
print("Spectrogram index shape:", spec_df.shape)
print("GTZAN text embedding shape:", gtzan_text_emb.shape)

print("\nMetadata source counts:")
print(metadata["source"].value_counts())

print("\nSpec index columns:", spec_df.columns.tolist())
print("\nMetadata columns:", metadata.columns.tolist())

"""## 4. Align spectrograms with metadata and text embeddings"""

gtzan_meta = metadata[metadata["source"] == "gtzan_whisper"].copy().reset_index(drop=True)

print("GTZAN metadata rows:", gtzan_meta.shape)
print("GTZAN text embeddings:", gtzan_text_emb.shape)

if len(gtzan_meta) != len(gtzan_text_emb):
    raise ValueError(
        f"Length mismatch: GTZAN metadata has {len(gtzan_meta)} rows, "
        f"but text embeddings have {len(gtzan_text_emb)} rows."
    )

gtzan_meta["gtzan_order"] = np.arange(len(gtzan_meta))

if "filename" not in spec_df.columns:
    raise ValueError("spec_index_gtzan500.csv must contain filename column.")

merged = spec_df.merge(
    gtzan_meta[["filename", "genre_label", "lyrics_text", "gtzan_order"]],
    on="filename",
    how="inner"
)

print("Merged paired audio-text rows:", merged.shape)
display(merged.head())

if len(merged) == 0:
    raise ValueError("No overlap between spectrogram index and GTZAN metadata filenames.")

text_indices = merged["gtzan_order"].values
X_text = gtzan_text_emb[text_indices]

print("Aligned text embeddings:", X_text.shape)

"""## 5. Load spectrogram tensors"""

specs = []
valid_rows = []
missing = []

for i, row in merged.iterrows():
    p = row["spec_path"]

    if isinstance(p, str) and os.path.exists(p):
        try:
            arr = np.load(p).astype(np.float32)

            if arr.ndim == 3:
                arr = arr[0]

            if arr.shape != (128, 128):
                fixed = np.zeros((128, 128), dtype=np.float32)
                h = min(128, arr.shape[0])
                w = min(128, arr.shape[1])
                fixed[:h, :w] = arr[:h, :w]
                arr = fixed

            specs.append(arr)
            valid_rows.append(i)
        except Exception as e:
            missing.append((i, str(e)))
    else:
        missing.append((i, "file missing"))

print("Loaded spectrograms:", len(specs))
print("Missing/invalid:", len(missing))

if len(specs) == 0:
    raise ValueError("No spectrograms loaded. Check spec_path values.")

merged_valid = merged.iloc[valid_rows].reset_index(drop=True)

X_spec = np.stack(specs)[:, np.newaxis, :, :]

text_indices_valid = merged_valid["gtzan_order"].values
X_text = gtzan_text_emb[text_indices_valid]

spec_min = X_spec.min()
spec_max = X_spec.max()

if np.isclose(spec_min, spec_max):
    raise ValueError("Spectrogram values are constant; cannot normalize.")

X_spec = 2.0 * (X_spec - spec_min) / (spec_max - spec_min + 1e-8) - 1.0
X_spec = X_spec.astype(np.float32)

y_genre = merged_valid["genre_label"].astype(str).values

le_genre = LabelEncoder()
y_genre_enc = le_genre.fit_transform(y_genre)

print("X_spec:", X_spec.shape)
print("X_text:", X_text.shape)
print("Genres:", list(le_genre.classes_))
print("Genre counts:")
print(pd.Series(y_genre).value_counts())

"""## 6. Visualize sample spectrograms"""

genres_unique = sorted(np.unique(y_genre))
n_show = min(10, len(genres_unique))

fig, axes = plt.subplots(2, 5, figsize=(15, 6))
axes = axes.flatten()

for ax, genre in zip(axes, genres_unique[:n_show]):
    idx = np.where(y_genre == genre)[0][0]
    ax.imshow(X_spec[idx, 0], origin="lower", aspect="auto")
    ax.set_title(genre)
    ax.axis("off")

for ax in axes[n_show:]:
    ax.axis("off")

plt.suptitle("Sample GTZAN Mel-Spectrograms")
plt.tight_layout()

sample_plot_path = f"{RESULTS_DIR}/spectrogram_samples.png"
plt.savefig(sample_plot_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", sample_plot_path)

"""## 7. Define Conv-VAE for spectrograms"""

class ConvEncoder(nn.Module):
    def __init__(self, latent_dim=32):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(32),
            nn.LeakyReLU(0.2),
            nn.Conv2d(32, 64, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(64),
            nn.LeakyReLU(0.2),
            nn.Conv2d(64, 128, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2),
            nn.Conv2d(128, 256, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2)
        )
        self.fc_mu = nn.Linear(256 * 8 * 8, latent_dim)
        self.fc_logv = nn.Linear(256 * 8 * 8, latent_dim)

    def forward(self, x):
        h = self.conv(x)
        h = h.view(x.size(0), -1)
        return self.fc_mu(h), self.fc_logv(h)


class ConvDecoder(nn.Module):
    def __init__(self, latent_dim=32):
        super().__init__()
        self.fc = nn.Linear(latent_dim, 256 * 8 * 8)
        self.deconv = nn.Sequential(
            nn.ConvTranspose2d(256, 128, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2),
            nn.ConvTranspose2d(128, 64, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(64),
            nn.LeakyReLU(0.2),
            nn.ConvTranspose2d(64, 32, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(32),
            nn.LeakyReLU(0.2),
            nn.ConvTranspose2d(32, 1, kernel_size=4, stride=2, padding=1),
            nn.Tanh()
        )

    def forward(self, z):
        h = self.fc(z).view(-1, 256, 8, 8)
        return self.deconv(h)


class ConvVAE(nn.Module):
    def __init__(self, latent_dim=32):
        super().__init__()
        self.encoder = ConvEncoder(latent_dim)
        self.decoder = ConvDecoder(latent_dim)

    def reparameterize(self, mu, logv):
        std = torch.exp(0.5 * logv)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x):
        mu, logv = self.encoder(x)
        z = self.reparameterize(mu, logv)
        xr = self.decoder(z)
        return xr, mu, logv

    def encode(self, x):
        mu, _ = self.encoder(x)
        return mu


def vae_loss(x, xr, mu, logv, beta=1.0):
    recon = F.mse_loss(xr, x, reduction="mean")
    kl = -0.5 * torch.mean(1 + logv - mu.pow(2) - logv.exp())
    return recon + beta * kl, recon, kl

"""## 8. Train Conv-VAE"""

LATENT_DIM = 32
EPOCHS = 60
BATCH_SIZE = 64
LR = 1e-3
BETA = 1.0

conv_vae = ConvVAE(latent_dim=LATENT_DIM).to(device)

spec_tensor = torch.tensor(X_spec, dtype=torch.float32)
dataset = TensorDataset(spec_tensor)
loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

optimizer = optim.Adam(conv_vae.parameters(), lr=LR, weight_decay=1e-5)

history = {"total": [], "recon": [], "kl": []}

conv_vae.train()

for epoch in range(1, EPOCHS + 1):
    total_epoch = 0.0
    recon_epoch = 0.0
    kl_epoch = 0.0

    for (xb,) in loader:
        xb = xb.to(device)
        optimizer.zero_grad()
        xr, mu, logv = conv_vae(xb)
        loss, recon, kl = vae_loss(xb, xr, mu, logv, beta=BETA)
        loss.backward()
        nn.utils.clip_grad_norm_(conv_vae.parameters(), 1.0)
        optimizer.step()

        total_epoch += loss.item()
        recon_epoch += recon.item()
        kl_epoch += kl.item()

    n_batches = len(loader)
    history["total"].append(total_epoch / n_batches)
    history["recon"].append(recon_epoch / n_batches)
    history["kl"].append(kl_epoch / n_batches)

    if epoch == 1 or epoch % 10 == 0:
        print(
            f"Epoch {epoch:03d}/{EPOCHS} | "
            f"Total={history['total'][-1]:.4f} | "
            f"Recon={history['recon'][-1]:.4f} | "
            f"KL={history['kl'][-1]:.4f}"
        )

print("Conv-VAE training complete.")

"""## 9. Plot training curves"""

plt.figure(figsize=(8, 5))
plt.plot(history["total"], label="Total")
plt.plot(history["recon"], label="Reconstruction")
plt.plot(history["kl"], label="KL")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Medium Task Conv-VAE Training Curves")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()

curve_path = f"{RESULTS_DIR}/conv_vae_training_curves.png"
plt.savefig(curve_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", curve_path)

"""## 10. Extract audio latent features"""

conv_vae.eval()

with torch.no_grad():
    Z_audio = conv_vae.encode(
        torch.tensor(X_spec, dtype=torch.float32).to(device)
    ).cpu().numpy()

print("Z_audio shape:", Z_audio.shape)

np.save(f"{RESULTS_DIR}/Z_audio_convvae.npy", Z_audio)
torch.save(conv_vae.state_dict(), f"{RESULTS_DIR}/conv_vae_medium_task.pth")

"""## 11. Prepare lyrics embeddings and fused representation"""

text_scaler = StandardScaler()
X_text_scaled = text_scaler.fit_transform(X_text).astype(np.float32)

pca_text = PCA(n_components=LATENT_DIM, random_state=SEED)
Z_text = pca_text.fit_transform(X_text_scaled)

Z_audio_scaled = StandardScaler().fit_transform(Z_audio)
Z_text_scaled = StandardScaler().fit_transform(Z_text)

Z_fused = np.concatenate([Z_audio_scaled, Z_text_scaled], axis=1)

print("Z_audio:", Z_audio_scaled.shape)
print("Z_text :", Z_text_scaled.shape)
print("Z_fused:", Z_fused.shape)
print("Text PCA variance explained:", pca_text.explained_variance_ratio_.sum())

np.save(f"{RESULTS_DIR}/Z_text_pca32.npy", Z_text_scaled)
np.save(f"{RESULTS_DIR}/Z_fused_audio_text.npy", Z_fused)

"""## 12. Define evaluation helper"""

def evaluate_clustering(X, labels_pred, y_true, method_name):
    labels_pred = np.asarray(labels_pred)
    valid_mask = labels_pred != -1

    n_clusters = len(set(labels_pred[valid_mask]))
    n_noise = int((labels_pred == -1).sum())

    row = {
        "method": method_name,
        "n_clusters": n_clusters,
        "n_noise": n_noise,
        "silhouette": np.nan,
        "davies_bouldin": np.nan,
        "calinski_harabasz": np.nan,
        "ari": np.nan
    }

    if n_clusters >= 2 and valid_mask.sum() > n_clusters:
        X_eval = X[valid_mask]
        pred_eval = labels_pred[valid_mask]
        y_eval = y_true[valid_mask]

        row["silhouette"] = silhouette_score(X_eval, pred_eval)
        row["davies_bouldin"] = davies_bouldin_score(X_eval, pred_eval)
        row["calinski_harabasz"] = calinski_harabasz_score(X_eval, pred_eval)
        row["ari"] = adjusted_rand_score(y_eval, pred_eval)

    return row


def run_all_clusterers(X, y_true, representation_name, k):
    results = []

    km = KMeans(n_clusters=k, random_state=SEED, n_init=10)
    pred_km = km.fit_predict(X)
    results.append(evaluate_clustering(X, pred_km, y_true, f"{representation_name} + KMeans"))

    agg = AgglomerativeClustering(n_clusters=k)
    pred_agg = agg.fit_predict(X)
    results.append(evaluate_clustering(X, pred_agg, y_true, f"{representation_name} + Agglomerative"))

    neigh = NearestNeighbors(n_neighbors=5)
    neigh.fit(X)
    distances, _ = neigh.kneighbors(X)
    eps = float(np.percentile(distances[:, -1], 85))

    db = DBSCAN(eps=eps, min_samples=5)
    pred_db = db.fit_predict(X)
    results.append(evaluate_clustering(X, pred_db, y_true, f"{representation_name} + DBSCAN"))

    return results

"""## 13. Run clustering experiments"""

K = len(np.unique(y_genre_enc))
print("Number of genre classes / k:", K)

all_results = []

all_results.extend(run_all_clusterers(Z_audio_scaled, y_genre_enc, "Conv-VAE audio latent", K))
all_results.extend(run_all_clusterers(Z_text_scaled, y_genre_enc, "Lyrics PCA latent", K))
all_results.extend(run_all_clusterers(Z_fused, y_genre_enc, "Fused audio+lyrics latent", K))

metrics_df = pd.DataFrame(all_results)

metrics_path = f"{RESULTS_DIR}/medium_task_clustering_metrics.csv"
metrics_df.to_csv(metrics_path, index=False)

print("Saved:", metrics_path)
metrics_df

"""## 14. Baseline comparison: PCA on flattened spectrograms"""

X_spec_flat = X_spec.reshape(X_spec.shape[0], -1)

pca_spec = PCA(n_components=LATENT_DIM, random_state=SEED)
Z_spec_pca = pca_spec.fit_transform(X_spec_flat)

baseline_results = run_all_clusterers(Z_spec_pca, y_genre_enc, "Direct spectral PCA", K)
baseline_df = pd.DataFrame(baseline_results)

combined_metrics = pd.concat([metrics_df, baseline_df], ignore_index=True)
combined_metrics_path = f"{RESULTS_DIR}/medium_task_all_metrics_with_baseline.csv"
combined_metrics.to_csv(combined_metrics_path, index=False)

print("PCA spectral variance explained:", pca_spec.explained_variance_ratio_.sum())
print("Saved:", combined_metrics_path)

combined_metrics

"""## 15. Metrics bar plots"""

plot_df = combined_metrics.copy()

plt.figure(figsize=(12, 5))
plt.bar(plot_df["method"], plot_df["silhouette"])
plt.xticks(rotation=75, ha="right")
plt.ylabel("Silhouette Score")
plt.title("Medium Task Clustering Comparison — Silhouette")
plt.tight_layout()

sil_plot_path = f"{RESULTS_DIR}/silhouette_comparison.png"
plt.savefig(sil_plot_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", sil_plot_path)

plt.figure(figsize=(12, 5))
plt.bar(plot_df["method"], plot_df["davies_bouldin"])
plt.xticks(rotation=75, ha="right")
plt.ylabel("Davies-Bouldin Index")
plt.title("Medium Task Clustering Comparison — Davies-Bouldin (lower is better)")
plt.tight_layout()

db_plot_path = f"{RESULTS_DIR}/davies_bouldin_comparison.png"
plt.savefig(db_plot_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", db_plot_path)

"""## 16. t-SNE visualization of fused latent space"""

perplexity_value = min(30, max(5, len(Z_fused)//10))

tsne = TSNE(
    n_components=2,
    random_state=SEED,
    perplexity=perplexity_value,
    init="pca",
    learning_rate="auto"
)

Z_tsne = tsne.fit_transform(Z_fused)

tsne_df = pd.DataFrame({
    "x": Z_tsne[:, 0],
    "y": Z_tsne[:, 1],
    "genre": y_genre,
})

plt.figure(figsize=(9, 7))

for genre in sorted(tsne_df["genre"].unique()):
    sub = tsne_df[tsne_df["genre"] == genre]
    plt.scatter(sub["x"], sub["y"], s=20, alpha=0.75, label=genre)

plt.title("t-SNE of Fused Audio + Lyrics Latent Space")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.grid(alpha=0.25)
plt.tight_layout()

tsne_path = f"{RESULTS_DIR}/tsne_fused_by_genre.png"
plt.savefig(tsne_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", tsne_path)

"""## 17. UMAP visualization of fused latent space"""

umap_model = umap.UMAP(
    n_components=2,
    random_state=SEED,
    n_neighbors=15,
    min_dist=0.1
)

Z_umap = umap_model.fit_transform(Z_fused)

umap_df = pd.DataFrame({
    "x": Z_umap[:, 0],
    "y": Z_umap[:, 1],
    "genre": y_genre,
})

plt.figure(figsize=(9, 7))

for genre in sorted(umap_df["genre"].unique()):
    sub = umap_df[umap_df["genre"] == genre]
    plt.scatter(sub["x"], sub["y"], s=20, alpha=0.75, label=genre)

plt.title("UMAP of Fused Audio + Lyrics Latent Space")
plt.xlabel("UMAP 1")
plt.ylabel("UMAP 2")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.grid(alpha=0.25)
plt.tight_layout()

umap_path = f"{RESULTS_DIR}/umap_fused_by_genre.png"
plt.savefig(umap_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", umap_path)

"""## 18. Reconstruction examples from Conv-VAE"""

conv_vae.eval()

n_examples = min(6, len(X_spec))
idxs = np.linspace(0, len(X_spec) - 1, n_examples, dtype=int)

with torch.no_grad():
    xb = torch.tensor(X_spec[idxs], dtype=torch.float32).to(device)
    xr, _, _ = conv_vae(xb)
    xr = xr.cpu().numpy()

fig, axes = plt.subplots(2, n_examples, figsize=(3 * n_examples, 6))

for j, idx in enumerate(idxs):
    axes[0, j].imshow(X_spec[idx, 0], origin="lower", aspect="auto")
    axes[0, j].set_title(f"Original\n{y_genre[idx]}")
    axes[0, j].axis("off")

    axes[1, j].imshow(xr[j, 0], origin="lower", aspect="auto")
    axes[1, j].set_title("Reconstructed")
    axes[1, j].axis("off")

plt.suptitle("Conv-VAE Spectrogram Reconstruction Examples")
plt.tight_layout()

recon_path = f"{RESULTS_DIR}/conv_vae_reconstructions.png"
plt.savefig(recon_path, dpi=150, bbox_inches="tight")
plt.show()

print("Saved:", recon_path)

"""## 19. Final summary"""

print("=" * 70)
print("MEDIUM TASK COMPLETE — SUMMARY")
print("=" * 70)

print(f'''
Dataset
  Paired GTZAN audio-text samples : {len(X_spec):,}
  Audio representation            : Mel-spectrograms {X_spec.shape[1:]}
  Text representation             : Whisper pseudo-lyrics embeddings reduced to {LATENT_DIM}D
  Number of genre labels          : {K}

Conv-VAE Architecture
  Input                           : 1 x 128 x 128 spectrogram
  Latent dim                      : {LATENT_DIM}
  Training epochs                 : {EPOCHS}
  Batch size                      : {BATCH_SIZE}
  Beta / KL weight                : {BETA}

Representations Compared
  1. Conv-VAE audio latent
  2. Lyrics PCA latent
  3. Fused audio + lyrics latent
  4. Direct spectral PCA baseline

Clustering Algorithms
  K-Means
  Agglomerative Clustering
  DBSCAN

Evaluation Metrics
  Silhouette Score
  Davies-Bouldin Index
  Adjusted Rand Index
  Calinski-Harabasz Index

Outputs saved to:
  {RESULTS_DIR}
''')

print("Top results by silhouette:")
display(combined_metrics.sort_values("silhouette", ascending=False).head(10))

"""

> For the Medium Task, we extend the basic VAE framework into a convolutional VAE that learns latent representations from GTZAN mel-spectrograms. To incorporate hybrid information, Whisper-generated pseudo-lyrics are embedded using a multilingual sentence embedding model and reduced to a compact latent representation. The final multimodal feature is constructed by concatenating the Conv-VAE audio latent vector with the lyric embedding representation. Clustering is evaluated using K-Means, Agglomerative Clustering, and DBSCAN, with Silhouette Score, Davies-Bouldin Index, and ARI used to compare representations.



> GTZAN lyrics are pseudo-lyrics generated by Whisper, so the text modality may contain transcription noise due to instrumental interference.
"""