# -*- coding: utf-8 -*-
"""medium_task_vae_with_8000.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ewdHaP1SQe-nBWxxDHy6mL_7wmSMwcb
"""

# ── 0. Install & imports ─────────────────────────────────────────────────────

!pip install -q umap-learn sentence-transformers

import os
import shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    silhouette_score,
    davies_bouldin_score,
    adjusted_rand_score,
    calinski_harabasz_score,
)
from sklearn.neighbors import NearestNeighbors
import umap

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device : {device}')
print(f'PyTorch: {torch.__version__}')

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)

os.makedirs('results/medium_task', exist_ok=True)

# ── 1. Load features from Drive ──────────────────────────────────────────────

from google.colab import drive
drive.mount('/content/drive')

FEAT_DIR = '/content/drive/MyDrive/VAE_Music_Project/features'
DATA_DIR = '/content/drive/MyDrive/VAE_Music_Project/data'

X_train  = np.load(f'{FEAT_DIR}/X_train.npy')
X_test   = np.load(f'{FEAT_DIR}/X_test.npy')
y_train  = np.load(f'{FEAT_DIR}/y_train.npy', allow_pickle=True)
y_test   = np.load(f'{FEAT_DIR}/y_test.npy',  allow_pickle=True)

X_mfcc_all = np.vstack([X_train, X_test])       # (1000, 80)
y_genre    = np.concatenate([y_train, y_test])   # (1000,)

hindi_emb   = np.load(f'{FEAT_DIR}/hindi_embeddings.npy')
english_emb = np.load(f'{FEAT_DIR}/english_embeddings.npy')

spec_df      = pd.read_csv(f'{FEAT_DIR}/spec_index.csv')
master_df    = pd.read_csv(f'{DATA_DIR}/metadata.csv')
bollywood_df = pd.read_csv(f'{DATA_DIR}/bollywood_clean.csv')

print('=== Features loaded ===')
print(f'MFCC all    : {X_mfcc_all.shape}')
print(f'Genre labels: {y_genre.shape}  unique={np.unique(y_genre).tolist()}')
print(f'Hindi emb   : {hindi_emb.shape}')
print(f'English emb : {english_emb.shape}')
print(f'Spec index  : {spec_df.shape}')

# ── 2. Load spectrograms —

print('Loading spectrograms...')
specs_list  = []
valid_idx   = []
missing_idx = []

project_root = os.path.dirname(FEAT_DIR)

for idx, row in spec_df.iterrows():
    # Construct the correct absolute path to the spectrogram
    # Assuming spec_path in spec_df is relative to the project_root
    current_spec_path = os.path.join(project_root, row['spec_path'])

    if os.path.exists(current_spec_path):
        s = np.load(current_spec_path).astype(np.float32)
        if s.shape != (128, 128):
            s = s[:128, :128] if s.ndim == 2 else s[0, :128, :128]
        specs_list.append(s)
        valid_idx.append(idx)
    else:
        missing_idx.append(idx)

if missing_idx:
    print(f'WARNING: {len(missing_idx)} spectrograms not found — excluded from training.')
    valid_mask = np.ones(len(spec_df), dtype=bool)
    valid_mask[missing_idx] = False
    # Ensure y_genre and X_mfcc_all are aligned only if they exist and are not already empty
    if y_genre.size > 0:
        y_genre    = y_genre[valid_mask]
    if X_mfcc_all.size > 0:
        X_mfcc_all = X_mfcc_all[valid_mask]
else:
    print('All spectrograms loaded successfully.')

# Only attempt to stack if specs_list is not empty
if specs_list:
    X_spec = np.stack(specs_list)[:, np.newaxis, :, :]   # (N, 1, 128, 128)

    # Normalise spectrograms globally to [-1, 1]
    spec_min = X_spec.min()
    spec_max = X_spec.max()
    X_spec   = 2.0 * (X_spec - spec_min) / (spec_max - spec_min + 1e-8) - 1.0

    print(f'Spectrograms loaded : {X_spec.shape}')
    print(f'Value range         : [{X_spec.min():.3f}, {X_spec.max():.3f}]')
    print(f'Genre labels shape  : {y_genre.shape}  (aligned with spectrograms)')

    # Visualise a sample from each genre
    genres_unique = np.unique(y_genre)
    fig, axes = plt.subplots(2, 5, figsize=(16, 6))
    for ax, genre in zip(axes.flat, genres_unique):
        idx = np.where(y_genre == genre)[0][0]
        ax.imshow(X_spec[idx, 0], origin='lower', aspect='auto', cmap='magma')
        ax.set_title(genre, fontsize=10)
        ax.axis('off')
    plt.suptitle('Sample mel-spectrograms per genre', fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig('results/medium_task/spectrogram_samples.png', dpi=150, bbox_inches='tight')
    plt.show()
    print('Saved: results/medium_task/spectrogram_samples.png')
else:
    print('ERROR: No spectrograms were loaded. Skipping spectrogram processing and visualization.')
    # Initialize X_spec and y_genre to empty arrays or handle the error appropriately
    # to prevent subsequent errors in the notebook if these variables are expected.
    X_spec = np.array([])
    y_genre = np.array([]) # Ensure y_genre is defined even if empty

# ── 2. Load spectrograms — filter missing files (BUG-1 FIX) ──────────────────

print('Loading spectrograms...')
specs_list = []
valid_idx = []
missing_idx = []

# Try a few sensible base directories for relative paths
candidate_roots = [
    "",  # use path as-is
    FEAT_DIR,
    os.path.dirname(FEAT_DIR),
    "/content",
    "/content/drive/MyDrive/VAE_Music_Project",
]

for idx, row in spec_df.iterrows():
    raw_path = str(row['spec_path']).strip()
    found_path = None

    # Case 1: already absolute and exists
    if os.path.isabs(raw_path) and os.path.exists(raw_path):
        found_path = raw_path
    else:
        # Case 2: try relative path under several possible roots
        for root in candidate_roots:
            test_path = os.path.normpath(os.path.join(root, raw_path))
            if os.path.exists(test_path):
                found_path = test_path
                break

        # Case 3: fallback by filename inside common spectrogram folders
        if found_path is None:
            fname = os.path.basename(raw_path)
            fallback_paths = [
                os.path.join(FEAT_DIR, "spectrograms", fname),
                os.path.join("/content/data/spectrograms", fname),
                os.path.join("/content/drive/MyDrive/VAE_Music_Project/data/spectrograms", fname),
            ]
            for test_path in fallback_paths:
                if os.path.exists(test_path):
                    found_path = test_path
                    break

    if found_path is not None:
        try:
            s = np.load(found_path).astype(np.float32)

            if s.ndim == 3:
                s = s[0]

            if s.shape != (128, 128):
                s_fixed = np.zeros((128, 128), dtype=np.float32)
                h = min(128, s.shape[0])
                w = min(128, s.shape[1])
                s_fixed[:h, :w] = s[:h, :w]
                s = s_fixed

            specs_list.append(s)
            valid_idx.append(idx)

        except Exception as e:
            print(f"Error loading spectrogram at row {idx}: {found_path} -> {e}")
            missing_idx.append(idx)
    else:
        missing_idx.append(idx)

print(f"Loaded spectrograms : {len(specs_list)}")
print(f"Missing/invalid     : {len(missing_idx)}")

if len(specs_list) == 0:
    raise ValueError(
        "No spectrograms were loaded. Check spec_df['spec_path'] values and where the .npy files are stored."
    )

# Keep only aligned rows
valid_mask = np.zeros(len(spec_df), dtype=bool)
valid_mask[valid_idx] = True

if len(y_genre) != len(spec_df):
    raise ValueError(f"Length mismatch: y_genre has {len(y_genre)} rows but spec_df has {len(spec_df)} rows.")

if len(X_mfcc_all) != len(spec_df):
    raise ValueError(f"Length mismatch: X_mfcc_all has {len(X_mfcc_all)} rows but spec_df has {len(spec_df)} rows.")

y_genre = y_genre[valid_mask]
X_mfcc_all = X_mfcc_all[valid_mask]

X_spec = np.stack(specs_list)[:, np.newaxis, :, :]   # (N, 1, 128, 128)

# Normalize to [-1, 1]
spec_min = X_spec.min()
spec_max = X_spec.max()

if np.isclose(spec_max, spec_min):
    raise ValueError("All loaded spectrogram values are constant. Normalization would be invalid.")

X_spec = 2.0 * (X_spec - spec_min) / (spec_max - spec_min + 1e-8) - 1.0

print(f"Spectrograms loaded : {X_spec.shape}")
print(f"Value range         : [{X_spec.min():.3f}, {X_spec.max():.3f}]")
print(f"Genre labels shape  : {y_genre.shape} (aligned with spectrograms)")

# Visualise a sample from each genre
genres_unique = np.unique(y_genre)
fig, axes = plt.subplots(2, 5, figsize=(16, 6))
axes = axes.flatten()

for ax, genre in zip(axes, genres_unique):
    genre_idx = np.where(y_genre == genre)[0][0]
    ax.imshow(X_spec[genre_idx, 0], origin='lower', aspect='auto', cmap='magma')
    ax.set_title(genre, fontsize=10)
    ax.axis('off')

# Hide unused axes if any
for ax in axes[len(genres_unique):]:
    ax.axis('off')

plt.suptitle('Sample mel-spectrograms per genre', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('results/medium_task/spectrogram_samples.png', dpi=150, bbox_inches='tight')
plt.show()

print('Saved: results/medium_task/spectrogram_samples.png')

# ── 2. Load spectrograms — filter missing files (BUG-1 FIX) ──────────────────

print('Loading spectrograms...')
specs_list  = []
valid_idx   = []
missing_idx = []

for idx, row in spec_df.iterrows():
    current_spec_path = str(row['spec_path']).strip()   # already full Drive path

    if os.path.exists(current_spec_path):
        s = np.load(current_spec_path).astype(np.float32)

        if s.ndim == 3:
            s = s[0]

        if s.shape != (128, 128):
            s_fixed = np.zeros((128, 128), dtype=np.float32)
            h = min(128, s.shape[0])
            w = min(128, s.shape[1])
            s_fixed[:h, :w] = s[:h, :w]
            s = s_fixed

        specs_list.append(s)
        valid_idx.append(idx)
    else:
        missing_idx.append(idx)

print(f'Loaded spectrograms : {len(specs_list)}')
print(f'Missing/invalid     : {len(missing_idx)}')

if len(specs_list) == 0:
    raise ValueError("No spectrograms were loaded. Check whether spec_index.csv contains valid Drive paths.")

valid_mask = np.zeros(len(spec_df), dtype=bool)
valid_mask[valid_idx] = True

if len(y_genre) != len(spec_df):
    raise ValueError(f"Length mismatch: y_genre has {len(y_genre)} rows but spec_df has {len(spec_df)} rows.")

if len(X_mfcc_all) != len(spec_df):
    raise ValueError(f"Length mismatch: X_mfcc_all has {len(X_mfcc_all)} rows but spec_df has {len(spec_df)} rows.")

y_genre = y_genre[valid_mask]
X_mfcc_all = X_mfcc_all[valid_mask]

X_spec = np.stack(specs_list)[:, np.newaxis, :, :]   # (N, 1, 128, 128)

# Normalize to [-1, 1]
spec_min = X_spec.min()
spec_max = X_spec.max()

if np.isclose(spec_max, spec_min):
    raise ValueError("All loaded spectrogram values are constant. Normalization would be invalid.")

X_spec = 2.0 * (X_spec - spec_min) / (spec_max - spec_min + 1e-8) - 1.0

print(f"Spectrograms loaded : {X_spec.shape}")
print(f"Value range         : [{X_spec.min():.3f}, {X_spec.max():.3f}]")
print(f"Genre labels shape  : {y_genre.shape} (aligned with spectrograms)")

# Visualise a sample from each genre
genres_unique = np.unique(y_genre)
fig, axes = plt.subplots(2, 5, figsize=(16, 6))
axes = axes.flatten()

for ax, genre in zip(axes, genres_unique):
    genre_idx = np.where(y_genre == genre)[0][0]
    ax.imshow(X_spec[genre_idx, 0], origin='lower', aspect='auto', cmap='magma')
    ax.set_title(genre, fontsize=10)
    ax.axis('off')

for ax in axes[len(genres_unique):]:
    ax.axis('off')

plt.suptitle('Sample mel-spectrograms per genre', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('results/medium_task/spectrogram_samples.png', dpi=150, bbox_inches='tight')
plt.show()

print('Saved: results/medium_task/spectrogram_samples.png')

# ── 3. Prepare lyrics embeddings

from sentence_transformers import SentenceTransformer

print('Loading sentence-transformer for genre text embeddings...')
st_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

GENRE_DESCRIPTIONS = {
    'blues'    : 'blues music slow melancholic guitar soulful emotional',
    'classical': 'classical orchestral instrumental composed symphonic',
    'country'  : 'country music acoustic guitar storytelling americana folk',
    'disco'    : 'disco upbeat danceable funky rhythmic electronic groove',
    'hiphop'   : 'hip hop rap urban rhythmic beats street spoken word',
    'jazz'     : 'jazz improvisation saxophone trumpet swing complex harmony',
    'metal'    : 'heavy metal aggressive loud distorted guitar fast intense',
    'pop'      : 'pop music catchy mainstream upbeat commercial radio',
    'reggae'   : 'reggae rhythmic caribbean offbeat bass laid back roots',
    'rock'     : 'rock music electric guitar drums powerful energetic band',
}

genre_names_ordered = sorted(GENRE_DESCRIPTIONS.keys())
genre_desc_texts    = [GENRE_DESCRIPTIONS[g] for g in genre_names_ordered]
genre_embeddings    = st_model.encode(genre_desc_texts, normalize_embeddings=True)
genre_emb_map       = dict(zip(genre_names_ordered, genre_embeddings))

# Assign each GTZAN track its genre-specific 384-dim embedding
lyrics_for_gtzan = np.stack([genre_emb_map[g] for g in y_genre])  # (N, 384)

scaler_lyr            = StandardScaler()
lyrics_for_gtzan_norm = scaler_lyr.fit_transform(lyrics_for_gtzan)

print('=== Lyrics preparation (FIXED) ===')
print(f'Lyrics matrix shape  : {lyrics_for_gtzan.shape}')
print(f'Unique vectors       : {len(np.unique(lyrics_for_gtzan, axis=0))}  (should be 10)')
print('Genre descriptions used:')
for g, desc in GENRE_DESCRIPTIONS.items():
    print(f'  {g:12s} → "{desc[:55]}"')

# ── 4. Conv-VAE architecture ──────────────────────────────────────────────────

class ConvEncoder(nn.Module):
    """4-layer conv encoder: 128→64→32→16→8 spatial, 1→32→64→128→256 channels."""
    def __init__(self, latent_dim=32):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1,   32,  kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(32),  nn.LeakyReLU(0.2),
            nn.Conv2d(32,  64,  kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(64),  nn.LeakyReLU(0.2),
            nn.Conv2d(64,  128, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(128), nn.LeakyReLU(0.2),
            nn.Conv2d(128, 256, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(256), nn.LeakyReLU(0.2),
        )
        self.fc_mu   = nn.Linear(256 * 8 * 8, latent_dim)
        self.fc_logv = nn.Linear(256 * 8 * 8, latent_dim)

    def forward(self, x):
        h = self.conv(x).view(x.size(0), -1)
        return self.fc_mu(h), self.fc_logv(h)


class ConvDecoder(nn.Module):
    """Mirror of ConvEncoder using transposed convolutions."""
    def __init__(self, latent_dim=32):
        super().__init__()
        self.fc = nn.Linear(latent_dim, 256 * 8 * 8)
        self.deconv = nn.Sequential(
            nn.ConvTranspose2d(256, 128, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(128), nn.LeakyReLU(0.2),
            nn.ConvTranspose2d(128, 64,  kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(64),  nn.LeakyReLU(0.2),
            nn.ConvTranspose2d(64,  32,  kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(32),  nn.LeakyReLU(0.2),
            nn.ConvTranspose2d(32,  1,   kernel_size=4, stride=2, padding=1),
            nn.Tanh(),
        )

    # BUG-3 FIX: Original applied F.leaky_relu() to the FC projection before
    # reshape. Large positive values produced by LeakyReLU were passed to the
    # deconv stack whose final Tanh must heavily saturate them, killing gradients.
    # Fix: pass the FC output directly — no activation before reshape.
    def forward(self, z):
        h = self.fc(z).view(-1, 256, 8, 8)   # removed: F.leaky_relu()
        return self.deconv(h)


class ConvVAE(nn.Module):
    def __init__(self, latent_dim=32):
        super().__init__()
        self.encoder    = ConvEncoder(latent_dim)
        self.decoder    = ConvDecoder(latent_dim)
        self.latent_dim = latent_dim

    def reparameterise(self, mu, logv):
        std = torch.exp(0.5 * logv)
        return mu + torch.randn_like(std) * std

    def forward(self, x):
        mu, logv = self.encoder(x)
        z        = self.reparameterise(mu, logv)
        return self.decoder(z), mu, logv

    def encode(self, x):
        mu, _ = self.encoder(x)
        return mu


class LyricsEncoder(nn.Module):
    """FC encoder: 384 → 256 → 128 → 32."""
    def __init__(self, input_dim=384, latent_dim=32):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 256), nn.BatchNorm1d(256), nn.LeakyReLU(0.2),
            nn.Linear(256, 128),       nn.BatchNorm1d(128), nn.LeakyReLU(0.2),
            nn.Linear(128, latent_dim),
        )

    def forward(self, x):
        return self.net(x)


LATENT_DIM = 32
conv_vae   = ConvVAE(latent_dim=LATENT_DIM).to(device)
lyrics_enc = LyricsEncoder(input_dim=384, latent_dim=LATENT_DIM).to(device)

vae_params    = sum(p.numel() for p in conv_vae.parameters()   if p.requires_grad)
lyrics_params = sum(p.numel() for p in lyrics_enc.parameters() if p.requires_grad)
print(f'Conv-VAE parameters  : {vae_params:,}')
print(f'Lyrics-FC parameters : {lyrics_params:,}')
print(f'Total parameters     : {vae_params + lyrics_params:,}')

with torch.no_grad():
    dummy_spec      = torch.zeros(4, 1, 128, 128).to(device)
    dummy_lyr       = torch.zeros(4, 384).to(device)
    recon, mu, logv = conv_vae(dummy_spec)
    z_lyr           = lyrics_enc(dummy_lyr)
    z_fused_dummy   = torch.cat([mu, z_lyr], dim=1)
    print(f'Encoder mu shape  : {mu.shape}')
    print(f'Decoder output    : {recon.shape}')
    print(f'Lyrics latent     : {z_lyr.shape}')
    print(f'Fused latent      : {z_fused_dummy.shape}')

# ── 5. Train Conv-VAE ─────────────────────────────────────────────────────────

EPOCHS_VAE = 80
BATCH_SIZE  = 32
LR_VAE      = 3e-4
BETA        = 1.0

spec_tensor = torch.tensor(X_spec,                dtype=torch.float32)
lyr_tensor  = torch.tensor(lyrics_for_gtzan_norm, dtype=torch.float32)
dataset_vae = TensorDataset(spec_tensor, lyr_tensor)
loader_vae  = DataLoader(dataset_vae, batch_size=BATCH_SIZE, shuffle=True,
                         num_workers=2, pin_memory=True)

# BUG-5 FIX (part 1): Separate optimisers keep the two networks independent.
# The original single optimiser let the lyrics alignment loss indirectly
# pull mu_audio toward a near-constant value (5 prototype targets), which,
# combined with the KL collapse from BUG-4, made Z_audio degenerate.
optimizer_vae = optim.Adam(conv_vae.parameters(),   lr=LR_VAE, weight_decay=1e-5)
optimizer_lyr = optim.Adam(lyrics_enc.parameters(), lr=LR_VAE, weight_decay=1e-5)

scheduler_vae = optim.lr_scheduler.CosineAnnealingLR(optimizer_vae, T_max=EPOCHS_VAE)
scheduler_lyr = optim.lr_scheduler.CosineAnnealingLR(optimizer_lyr, T_max=EPOCHS_VAE)


# BUG-4 FIX: Correct ELBO loss formulation
#
# ORIGINAL BUG:
#   recon = F.mse_loss(x_recon, x, reduction='mean')
#               → divides by B × C × H × W = 32 × 1 × 128 × 128 = 524 288
#   kl    = -0.5 * torch.mean(1 + logv - mu² - exp(logv))
#               → divides by B × latent_dim = 32 × 32 = 1 024
#
# The ~512× scale difference caused KL to dominate, driving posterior collapse:
# the encoder ignored the input and output N(0,I) for every sample, making all
# latents nearly identical. This is why Silhouette → 1.0 and n_clusters → 1.
#
# FIX: Use reduction='sum' then divide by batch size for both terms so that
# recon and KL are both normalised per-sample regardless of tensor dimensions.
def vae_loss_fn(x, x_recon, mu, logv, beta=1.0):
    B     = x.size(0)
    recon = F.mse_loss(x_recon, x, reduction='sum') / B
    kl    = -0.5 * (1 + logv - mu.pow(2) - logv.exp()).sum(dim=1).mean()
    return recon + beta * kl, recon, kl


# BUG-5 FIX (part 2): Cosine alignment loss instead of MSE
#
# ORIGINAL BUG:
#   lyr_align_loss = F.mse_loss(z_lyr, mu_audio.detach())
#
# MSE alignment pushes the lyrics encoder to copy mu_audio exactly in magnitude
# and direction. With only 5 (later 10) distinct targets out of 1000 samples,
# the lyrics encoder collapses to a near-constant output. The fixed loss below
# only aligns directions (angular similarity), preserving the relative geometry
# of the 10 distinct genre embeddings.
def lyrics_align_loss_fn(z_lyr, mu_audio):
    return (1.0 - F.cosine_similarity(z_lyr, mu_audio.detach(), dim=1)).mean()


history = {'total': [], 'recon': [], 'kl': [], 'lyr_align': []}

conv_vae.train()
lyrics_enc.train()

for epoch in range(1, EPOCHS_VAE + 1):
    ep_total = ep_recon = ep_kl = ep_lyr = 0.0

    for xb_spec, xb_lyr in loader_vae:
        xb_spec = xb_spec.to(device)
        xb_lyr  = xb_lyr.to(device)

        # VAE update — audio modality only
        optimizer_vae.zero_grad()
        x_recon, mu_audio, logv_audio = conv_vae(xb_spec)
        loss_vae, recon, kl = vae_loss_fn(xb_spec, x_recon, mu_audio, logv_audio, BETA)
        loss_vae.backward()
        nn.utils.clip_grad_norm_(conv_vae.parameters(), max_norm=1.0)
        optimizer_vae.step()

        # Lyrics encoder update — independent of VAE gradients
        optimizer_lyr.zero_grad()
        z_lyr      = lyrics_enc(xb_lyr)
        align_loss = lyrics_align_loss_fn(z_lyr, mu_audio)
        align_loss.backward()
        nn.utils.clip_grad_norm_(lyrics_enc.parameters(), max_norm=1.0)
        optimizer_lyr.step()

        ep_total += (loss_vae + 0.1 * align_loss).item()
        ep_recon += recon.item()
        ep_kl    += kl.item()
        ep_lyr   += align_loss.item()

    scheduler_vae.step()
    scheduler_lyr.step()

    n = len(loader_vae)
    for key, val in zip(['total', 'recon', 'kl', 'lyr_align'],
                        [ep_total, ep_recon, ep_kl, ep_lyr]):
        history[key].append(val / n)

    if epoch % 10 == 0 or epoch == 1:
        print(f'Epoch {epoch:3d}/{EPOCHS_VAE} | '
              f'Total={history["total"][-1]:.4f} | '
              f'Recon={history["recon"][-1]:.4f} | '
              f'KL={history["kl"][-1]:.4f} | '
              f'LyrAlign={history["lyr_align"][-1]:.4f}')

print('\nTraining complete.')

fig, axes = plt.subplots(1, 4, figsize=(18, 4))
titles  = ['Total Loss', 'Reconstruction', 'KL Divergence', 'Lyrics Alignment']
keys    = ['total', 'recon', 'kl', 'lyr_align']
colours = ['#3B6FCC', '#D85A30', '#1D9E75', '#7F77DD']
for ax, title, key, c in zip(axes, titles, keys, colours):
    ax.plot(history[key], color=c, linewidth=2)
    ax.set_title(title, fontsize=11)
    ax.set_xlabel('Epoch')
    ax.grid(alpha=0.3)
    ax.spines[['top', 'right']].set_visible(False)
plt.suptitle('Conv-VAE Training Curves (Medium Task)', fontsize=13, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('results/medium_task/training_curves.png', dpi=150, bbox_inches='tight')
plt.show()

# ── 6. Reconstruction examples ────────────────────────────────────────────────

conv_vae.eval()
n_examples   = 5
genres_shown = ['blues', 'classical', 'disco', 'metal', 'pop']
indices      = [np.where(y_genre == g)[0][0] for g in genres_shown]

fig, axes = plt.subplots(2, n_examples, figsize=(16, 6))
with torch.no_grad():
    for col, (idx, genre) in enumerate(zip(indices, genres_shown)):
        xb            = torch.tensor(X_spec[[idx]], dtype=torch.float32).to(device)
        x_recon, _, _ = conv_vae(xb)
        orig          = X_spec[idx, 0]
        recon_np      = x_recon.cpu().numpy()[0, 0]

        axes[0, col].imshow(orig,     origin='lower', aspect='auto', cmap='magma', vmin=-1, vmax=1)
        axes[1, col].imshow(recon_np, origin='lower', aspect='auto', cmap='magma', vmin=-1, vmax=1)
        axes[0, col].set_title(f'{genre}\n(original)',      fontsize=9)
        axes[1, col].set_title(f'{genre}\n(reconstructed)', fontsize=9)
        for ax in [axes[0, col], axes[1, col]]:
            ax.set_xticks([]); ax.set_yticks([])

plt.suptitle('Spectrogram Reconstruction — Conv-VAE', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('results/medium_task/reconstructions.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/medium_task/reconstructions.png')

# ── 7. Extract hybrid fused latent representations ────────────────────────────

conv_vae.eval()
lyrics_enc.eval()

with torch.no_grad():
    z_audio_list = []
    for i in range(0, len(X_spec), 64):
        xb = torch.tensor(X_spec[i:i+64], dtype=torch.float32).to(device)
        z_audio_list.append(conv_vae.encode(xb).cpu().numpy())
    Z_audio = np.vstack(z_audio_list)                                       # (N, 32)

    lyr_t    = torch.tensor(lyrics_for_gtzan_norm, dtype=torch.float32).to(device)
    Z_lyrics = lyrics_enc(lyr_t).cpu().numpy()                              # (N, 32)

Z_fused = np.hstack([Z_audio, Z_lyrics])                                    # (N, 64)

print(f'Z_audio  shape: {Z_audio.shape}')
print(f'Z_lyrics shape: {Z_lyrics.shape}')
print(f'Z_fused  shape: {Z_fused.shape}  <- clustering input')

# Sanity check — degenerate latents cause n_clusters=1 downstream
print(f'\nZ_audio  std min across dims: {Z_audio.std(axis=0).min():.6f}  (must be > 0)')
print(f'Z_lyrics std min across dims: {Z_lyrics.std(axis=0).min():.6f}  (must be > 0)')
print(f'Z_fused  std min across dims: {Z_fused.std(axis=0).min():.6f}   (must be > 0)')

np.save('results/medium_task/Z_audio.npy',  Z_audio)
np.save('results/medium_task/Z_lyrics.npy', Z_lyrics)
np.save('results/medium_task/Z_fused.npy',  Z_fused)
np.save('results/medium_task/y_genre.npy',  y_genre)
print('Latents saved.')

# ── 8. Clustering — K-Means, Agglomerative, DBSCAN ───────────────────────────

K = 10   # 10 GTZAN genres

# 8a. K-Means
print('Fitting K-Means...')
km        = KMeans(n_clusters=K, random_state=SEED, n_init=20, max_iter=500)
labels_km = km.fit_predict(Z_fused)
print(f'K-Means done. Cluster sizes: {dict(zip(*np.unique(labels_km, return_counts=True)))}')

# 8b. Agglomerative Clustering
print('Fitting Agglomerative Clustering (Ward)...')
agg        = AgglomerativeClustering(n_clusters=K, linkage='ward')
labels_agg = agg.fit_predict(Z_fused)
print(f'Agglomerative done. Cluster sizes: {dict(zip(*np.unique(labels_agg, return_counts=True)))}')

# 8c. DBSCAN — BUG-6 FIX
#
# ORIGINAL BUG: eps was set to the 15th percentile of k-NN distances.
# The comment said "knee point" but 15th percentile picks a very small eps
# that labels nearly all points as noise. The fallback at 30th percentile
# is also too small for a 64-dim VAE latent.
#
# FIX: Detect the true elbow of the sorted k-NN distance curve using the
# point of maximum second-order difference (curvature). This corresponds to
# the genuine density boundary rather than an arbitrary low percentile.

print('Finding optimal DBSCAN eps via k-NN elbow detection...')
k_nn  = 10
nbrs  = NearestNeighbors(n_neighbors=k_nn).fit(Z_fused)
distances, _ = nbrs.kneighbors(Z_fused)

knn_dists_asc = np.sort(distances[:, -1])   # ascending for curvature analysis

# Elbow = index of maximum second-order difference
if len(knn_dists_asc) > 4:
    d2       = np.diff(knn_dists_asc, n=2)
    elbow_i  = int(np.argmax(d2)) + 1        # +1 accounts for diff offset
    eps_auto = float(knn_dists_asc[elbow_i])
else:
    eps_auto = float(np.percentile(knn_dists_asc, 90))

print(f'Auto-selected eps = {eps_auto:.4f}  (elbow of k-NN distance curve)')

# Plot with elbow marked (display sorted descending, as is conventional)
knn_dists_desc = knn_dists_asc[::-1]
plt.figure(figsize=(8, 4))
plt.plot(knn_dists_desc, color='#3B6FCC', linewidth=2)
elbow_plot_i = len(knn_dists_desc) - elbow_i - 1
plt.axvline(elbow_plot_i, color='#E24B4A', linestyle='--', linewidth=1.5,
            label=f'eps = {eps_auto:.4f}')
plt.xlabel('Points (sorted descending)')
plt.ylabel(f'{k_nn}-NN distance')
plt.title('k-NN distance plot for DBSCAN eps selection', fontsize=12)
plt.legend(fontsize=9)
plt.grid(alpha=0.3)
plt.gca().spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.savefig('results/medium_task/dbscan_knn_plot.png', dpi=150, bbox_inches='tight')
plt.show()

MIN_SAMPLES = 5
db        = DBSCAN(eps=eps_auto, min_samples=MIN_SAMPLES, metric='euclidean', n_jobs=-1)
labels_db = db.fit_predict(Z_fused)

n_clusters_db = len(set(labels_db)) - (1 if -1 in labels_db else 0)
n_noise_db    = (labels_db == -1).sum()

print(f'DBSCAN eps={eps_auto:.4f}, min_samples={MIN_SAMPLES}')
print(f'  Clusters found : {n_clusters_db}')
print(f'  Noise points   : {n_noise_db} ({100*n_noise_db/len(labels_db):.1f}%)')
if n_clusters_db >= 1:
    print(f'  Cluster sizes  : {dict(zip(*np.unique(labels_db[labels_db>=0], return_counts=True)))}')

# Fallback to 95th percentile if still degenerate
if n_clusters_db < 2:
    eps_auto  = float(np.percentile(knn_dists_asc, 95))
    db        = DBSCAN(eps=eps_auto, min_samples=MIN_SAMPLES, metric='euclidean', n_jobs=-1)
    labels_db = db.fit_predict(Z_fused)
    n_clusters_db = len(set(labels_db)) - (1 if -1 in labels_db else 0)
    n_noise_db    = (labels_db == -1).sum()
    print(f'  Retried with eps={eps_auto:.4f} (95th pct): {n_clusters_db} clusters, {n_noise_db} noise')

np.save('results/medium_task/labels_kmeans.npy', labels_km)
np.save('results/medium_task/labels_agg.npy',    labels_agg)
np.save('results/medium_task/labels_dbscan.npy', labels_db)

# ── 9. UMAP visualisations ────────────────────────────────────────────────────

print('Running UMAP on fused latent...')
reducer = umap.UMAP(n_components=2, n_neighbors=20, min_dist=0.1,
                    random_state=SEED, metric='euclidean')
Z_umap = reducer.fit_transform(Z_fused)
print(f'UMAP done: {Z_umap.shape}')
np.save('results/medium_task/Z_umap_fused.npy', Z_umap)

reducer_audio = umap.UMAP(n_components=2, n_neighbors=20, min_dist=0.1, random_state=SEED)
Z_umap_audio  = reducer_audio.fit_transform(Z_audio)
np.save('results/medium_task/Z_umap_audio.npy', Z_umap_audio)
print(f'UMAP (audio only) done: {Z_umap_audio.shape}')

GENRE_PALETTE = {
    'blues':'#185FA5','classical':'#7F77DD','country':'#639922',
    'disco':'#D4537E','hiphop':'#5F5E5A','jazz':'#1D9E75',
    'metal':'#E24B4A','pop':'#EF9F27','reggae':'#D85A30','rock':'#3B6FCC'
}
CLUSTER_PAL = [
    '#E24B4A','#378ADD','#1D9E75','#EF9F27','#7F77DD',
    '#D85A30','#639922','#D4537E','#185FA5','#5F5E5A'
]

c_genre = [GENRE_PALETTE[g] for g in y_genre]
c_km    = [CLUSTER_PAL[l % len(CLUSTER_PAL)] for l in labels_km]
c_agg   = [CLUSTER_PAL[l % len(CLUSTER_PAL)] for l in labels_agg]
c_db    = ['#cccccc' if l == -1 else CLUSTER_PAL[l % len(CLUSTER_PAL)] for l in labels_db]

fig, axes = plt.subplots(2, 4, figsize=(22, 11))

def sp(ax, embed, colours, title, s=10, alpha=0.7):
    ax.scatter(embed[:, 0], embed[:, 1], c=colours, s=s, alpha=alpha, linewidths=0)
    ax.set_title(title, fontsize=10)
    ax.set_xlabel('UMAP-1'); ax.set_ylabel('UMAP-2')
    ax.spines[['top', 'right']].set_visible(False)

patches = [mpatches.Patch(color=v, label=k) for k, v in GENRE_PALETTE.items()]
sp(axes[0, 0], Z_umap, c_genre, 'Fused latent — true genre', s=12)
axes[0, 0].legend(handles=patches, fontsize=6, ncol=2, loc='upper right')
sp(axes[0, 1], Z_umap, c_km,  f'Fused — K-Means (k={K})')
sp(axes[0, 2], Z_umap, c_agg, f'Fused — Agglomerative (k={K})')
sp(axes[0, 3], Z_umap, c_db,
   f'Fused — DBSCAN\n({n_clusters_db} clusters, {n_noise_db} noise)')

sp(axes[1, 0], Z_umap_audio, c_genre, 'Audio-only latent — true genre', s=12)
axes[1, 0].legend(handles=patches, fontsize=6, ncol=2, loc='upper right')

km_audio  = KMeans(n_clusters=K, random_state=SEED, n_init=10).fit_predict(Z_audio)
agg_audio = AgglomerativeClustering(n_clusters=K, linkage='ward').fit_predict(Z_audio)
c_km_a    = [CLUSTER_PAL[l % len(CLUSTER_PAL)] for l in km_audio]
c_agg_a   = [CLUSTER_PAL[l % len(CLUSTER_PAL)] for l in agg_audio]

sp(axes[1, 1], Z_umap_audio, c_km_a,  'Audio-only — K-Means')
sp(axes[1, 2], Z_umap_audio, c_agg_a, 'Audio-only — Agglomerative')
axes[1, 3].axis('off')
axes[1, 3].text(0.5, 0.5, 'Row 0: Hybrid fused\nRow 1: Audio-only\n(modality ablation)',
               ha='center', va='center', fontsize=11, transform=axes[1, 3].transAxes)

plt.suptitle('UMAP Visualisations — Hybrid Fused Latent vs Audio-Only (Medium Task)',
             fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('results/medium_task/umap_all_methods.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/medium_task/umap_all_methods.png')

# ── 10. Evaluation — Silhouette, Davies-Bouldin, ARI ─────────────────────────
#
# BUG-7 FIX: The original code created y_int once at shape (1000,) and reused
# it for every evaluate_clustering call. If BUG-1 reduced the dataset size (e.g.
# to 990 tracks), y_int was still length 1000 and the slice t_m = true_labels[mask]
# would index out of bounds or silently misalign for DBSCAN-masked subsets.
#
# FIX: Pass y_genre (string labels) directly to evaluate_clustering and let the
# function re-encode them with LabelEncoder internally after applying any noise
# mask. This guarantees t_int always matches Z_m and p_m exactly.

def evaluate_clustering(Z, pred_labels, true_labels, name, skip_noise=True):
    """
    Compute Silhouette, Davies-Bouldin, and ARI.
    - Noise points (-1) from DBSCAN are excluded.
    - true_labels can be strings or ints; re-encoded internally per subset.
    """
    pred_labels = np.asarray(pred_labels)
    true_labels = np.asarray(true_labels)

    if skip_noise and -1 in pred_labels:
        mask        = pred_labels != -1
        Z_m         = Z[mask]
        p_m         = pred_labels[mask]
        t_m         = true_labels[mask]
        note        = f'(excl. {(~mask).sum()} noise points)'
    else:
        Z_m, p_m, t_m, note = Z, pred_labels, true_labels, ''

    # Re-encode true labels to ints (safe for any subset size or label type)
    t_int    = LabelEncoder().fit_transform(t_m)
    n_unique = len(np.unique(p_m))

    if n_unique < 2:
        print(f'  {name:45s}  SKIP — only {n_unique} cluster(s); check for degenerate latents')
        return {
            'method': name, 'n_clusters': n_unique,
            'silhouette': np.nan, 'davies_bouldin': np.nan,
            'ARI': np.nan, 'note': 'too few clusters',
        }

    sil = silhouette_score(Z_m, p_m, sample_size=min(2000, len(Z_m)), random_state=SEED)
    db  = davies_bouldin_score(Z_m, p_m)
    ari = adjusted_rand_score(t_int, p_m)

    print(f'  {name:45s}  Sil={sil:.4f}  DB={db:.4f}  ARI={ari:.4f}  {note}')
    return {
        'method'        : name,
        'n_clusters'    : n_unique,
        'silhouette'    : round(sil, 4),
        'davies_bouldin': round(db,  4),
        'ARI'           : round(ari, 4),
        'note'          : note,
    }


print('=== Clustering Evaluation — Medium Task ===')
results = []

# Conv-VAE fused latent
results.append(evaluate_clustering(Z_fused, labels_km,  y_genre, 'Conv-VAE Fused + K-Means'))
results.append(evaluate_clustering(Z_fused, labels_agg, y_genre, 'Conv-VAE Fused + Agglomerative'))
results.append(evaluate_clustering(Z_fused, labels_db,  y_genre, 'Conv-VAE Fused + DBSCAN'))

# Audio-only latent
results.append(evaluate_clustering(Z_audio, km_audio,  y_genre, 'Conv-VAE Audio-only + K-Means'))
results.append(evaluate_clustering(Z_audio, agg_audio, y_genre, 'Conv-VAE Audio-only + Agglomerative'))

# PCA baselines
pca         = PCA(n_components=32, random_state=SEED)
X_spec_flat = X_spec.reshape(len(X_spec), -1)    # (N, 16384)
Z_pca_spec  = pca.fit_transform(X_spec_flat)
labels_pca_km  = KMeans(n_clusters=K, random_state=SEED, n_init=20).fit_predict(Z_pca_spec)
labels_pca_agg = AgglomerativeClustering(n_clusters=K, linkage='ward').fit_predict(Z_pca_spec)
results.append(evaluate_clustering(Z_pca_spec, labels_pca_km,  y_genre, 'PCA (spec) + K-Means'))
results.append(evaluate_clustering(Z_pca_spec, labels_pca_agg, y_genre, 'PCA (spec) + Agglomerative'))

pca_mfcc        = PCA(n_components=32, random_state=SEED)
Z_pca_mfcc      = pca_mfcc.fit_transform(X_mfcc_all)
labels_pca_mfcc = KMeans(n_clusters=K, random_state=SEED, n_init=20).fit_predict(Z_pca_mfcc)
results.append(evaluate_clustering(Z_pca_mfcc, labels_pca_mfcc, y_genre, 'PCA (MFCC) + K-Means'))

results_df = pd.DataFrame(results)
results_df.to_csv('results/medium_task/clustering_metrics.csv', index=False)
print('\nFull results table:')
print(results_df[['method', 'n_clusters', 'silhouette', 'davies_bouldin', 'ARI']].to_string(index=False))

# Metric comparison bar chart
valid_df = results_df.dropna(subset=['silhouette', 'davies_bouldin', 'ARI'])

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
methods_short = [
    m.replace('Conv-VAE Fused + ', 'CVF-').replace('Conv-VAE Audio-only + ', 'CVA-')
     .replace('PCA (spec) + ', 'PCA-S-').replace('PCA (MFCC) + ', 'PCA-M-')
    for m in valid_df['method']
]
bar_colours = []
for m in valid_df['method']:
    if 'Fused'       in m: bar_colours.append('#378ADD')
    elif 'Audio-only' in m: bar_colours.append('#1D9E75')
    else:                    bar_colours.append('#EF9F27')

x = range(len(valid_df))
for ax, col, title in zip(
        axes,
        ['silhouette', 'davies_bouldin', 'ARI'],
        ['Silhouette Score\n(higher = better)',
         'Davies-Bouldin Index\n(lower = better)',
         'Adjusted Rand Index\n(higher = better)']):
    bars = ax.bar(x, valid_df[col], color=bar_colours, edgecolor='white', width=0.6)
    ax.set_title(title, fontsize=11)
    ax.set_xticks(x)
    ax.set_xticklabels(methods_short, rotation=45, ha='right', fontsize=7)
    ax.spines[['top', 'right']].set_visible(False)
    for bar, v in zip(bars, valid_df[col]):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.005,
                f'{v:.3f}', ha='center', va='bottom', fontsize=7)

legend_patches = [
    mpatches.Patch(color='#378ADD', label='Conv-VAE Fused (audio+lyrics)'),
    mpatches.Patch(color='#1D9E75', label='Conv-VAE Audio-only'),
    mpatches.Patch(color='#EF9F27', label='PCA baseline'),
]
fig.legend(handles=legend_patches, loc='lower center', ncol=3, fontsize=9,
           bbox_to_anchor=(0.5, -0.05))
plt.suptitle('Clustering Evaluation — Medium Task', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('results/medium_task/metrics_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/medium_task/metrics_comparison.png')

# ── 11. Cluster composition — genre purity ────────────────────────────────────

def cluster_purity(true_labels, pred_labels):
    """Fraction of tracks in the dominant true class per cluster."""
    total = 0
    n     = len(true_labels)
    for cluster_id in np.unique(pred_labels):
        if cluster_id == -1:
            continue
        mask   = pred_labels == cluster_id
        counts = np.bincount(LabelEncoder().fit_transform(true_labels[mask]))
        total += counts.max()
    return total / n

purity_km  = cluster_purity(y_genre, labels_km)
purity_agg = cluster_purity(y_genre, labels_agg)
purity_db  = cluster_purity(y_genre, labels_db)

print('=== Cluster Purity (genre, GTZAN) ===')
print(f'K-Means        : {purity_km:.4f}')
print(f'Agglomerative  : {purity_agg:.4f}')
print(f'DBSCAN         : {purity_db:.4f}')

comp_df    = pd.DataFrame({'cluster': labels_km, 'genre': y_genre})
pivot      = comp_df.groupby(['cluster', 'genre']).size().unstack(fill_value=0)
pivot_norm = pivot.div(pivot.sum(axis=1), axis=0)

fig, ax = plt.subplots(figsize=(13, 5))
im = ax.imshow(pivot_norm.values, cmap='YlOrRd', aspect='auto', vmin=0, vmax=1)
ax.set_xticks(range(len(pivot_norm.columns)))
ax.set_xticklabels(pivot_norm.columns, rotation=45, ha='right')
ax.set_yticks(range(len(pivot_norm.index)))
ax.set_yticklabels([f'Cluster {i}' for i in pivot_norm.index])
ax.set_title('K-Means Cluster Composition — Genre fraction per cluster\n(Conv-VAE Fused)', fontsize=12)
ax.set_xlabel('Genre')
for i in range(len(pivot_norm.index)):
    for j in range(len(pivot_norm.columns)):
        val = pivot_norm.values[i, j]
        ax.text(j, i, f'{val:.2f}', ha='center', va='center',
                fontsize=7, color='black' if val < 0.6 else 'white')
plt.colorbar(im, ax=ax, label='Fraction of cluster')
plt.tight_layout()
plt.savefig('results/medium_task/cluster_composition_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: results/medium_task/cluster_composition_heatmap.png')

# ── 12. Comparative analysis ──────────────────────────────────────────────────
#


print('=' * 65)
print('COMPARATIVE ANALYSIS — MEDIUM TASK')
print('=' * 65)

fused_km = results_df[results_df['method'] == 'Conv-VAE Fused + K-Means'].iloc[0]
audio_km = results_df[results_df['method'] == 'Conv-VAE Audio-only + K-Means'].iloc[0]
pca_km   = results_df[results_df['method'] == 'PCA (spec) + K-Means'].iloc[0]   # FIXED

def _fmt(val):
    return f'{val:.4f}' if not pd.isna(val) else 'N/A (degenerate latent)'

print(f"""
1. CONV-VAE FUSED vs PCA BASELINE
   Silhouette : {_fmt(fused_km['silhouette'])} (VAE)  vs  {_fmt(pca_km['silhouette'])} (PCA)
   DB Index   : {_fmt(fused_km['davies_bouldin'])} (VAE)  vs  {_fmt(pca_km['davies_bouldin'])} (PCA)
   ARI        : {_fmt(fused_km['ARI'])} (VAE)  vs  {_fmt(pca_km['ARI'])} (PCA)

   Why VAE typically wins:
   - PCA is a linear projection — it cannot capture non-linear structure in
     spectrograms (harmonic patterns, rhythm periodicity). The Conv-VAE
     encoder learns hierarchical spectral features through successive
     downsampling, producing a semantically richer latent space.
   - KL regularisation forces a smooth, continuous latent space that
     benefits downstream K-Means (clusters are more Gaussian-shaped).

2. HYBRID FUSION vs AUDIO-ONLY
   Silhouette : {_fmt(fused_km['silhouette'])} (fused)  vs  {_fmt(audio_km['silhouette'])} (audio-only)
   DB Index   : {_fmt(fused_km['davies_bouldin'])} (fused)  vs  {_fmt(audio_km['davies_bouldin'])} (audio-only)
   ARI        : {_fmt(fused_km['ARI'])} (fused)  vs  {_fmt(audio_km['ARI'])} (audio-only)

   Interpretation:
   - If fused > audio-only: genre-text lyrics embeddings carry complementary
     semantic information (mood, theme) that disambiguates genres with similar
     acoustic profiles (e.g. blues vs country, pop vs disco).
   - If fused ≈ audio-only: the prototype strategy introduces noise since GTZAN
     has no real paired lyrics. Building a dataset with genuine audio-lyric
     pairs (Hard Task) would improve this.

3. CLUSTERING ALGORITHM COMPARISON
   K-Means      : Sil={_fmt(fused_km['silhouette'])} | DB={_fmt(fused_km['davies_bouldin'])} | ARI={_fmt(fused_km['ARI'])}
   Agglomerative: Sil={_fmt(results_df[results_df['method']=='Conv-VAE Fused + Agglomerative']['silhouette'].values[0])}
   DBSCAN       : clusters={n_clusters_db}, noise={n_noise_db}

   - K-Means assumes spherical equal-size clusters — best when KL regularisation
     keeps the latent space well-structured.
   - Agglomerative (Ward) is more robust to non-spherical cluster shapes and
     does not require a good initialisation.
   - DBSCAN detects arbitrary density-connected shapes and marks outliers as
     noise — sensitive to eps; the elbow plot should be used to calibrate.
""")

# ── 13. Save model and all results to Drive ───────────────────────────────────

SAVE_DIR = '/content/drive/MyDrive/VAE_Music_Project/results/medium_task'
os.makedirs(SAVE_DIR, exist_ok=True)

torch.save(conv_vae.state_dict(),   f'{SAVE_DIR}/conv_vae.pth')
torch.save(lyrics_enc.state_dict(), f'{SAVE_DIR}/lyrics_encoder.pth')

for fname in os.listdir('results/medium_task'):
    shutil.copy(f'results/medium_task/{fname}', f'{SAVE_DIR}/{fname}')

print('=== All results saved to Drive ===')
for f in sorted(os.listdir(SAVE_DIR)):
    size = os.path.getsize(f'{SAVE_DIR}/{f}') / 1024
    print(f'  {f:45s}  {size:.1f} KB')

# ── 14. Summary ───────────────────────────────────────────────────────────────

print('=' * 65)
print('MEDIUM TASK COMPLETE — SUMMARY')
print('=' * 65)
print(f"""
Architecture
  Conv-VAE encoder  : 4 x Conv2d (1->32->64->128->256), BN + LeakyReLU
  Conv-VAE decoder  : 4 x ConvTranspose2d (mirror) + Tanh
                      [BUG-3 FIXED: removed LeakyReLU before FC reshape]
  Lyrics FC encoder : 384 -> 256 -> 128 -> 32

  Fused latent dim  : 64  (32 audio + 32 lyrics)

Training
  Epochs    : {EPOCHS_VAE}  |  Batch: {BATCH_SIZE}  |  LR: {LR_VAE}  |  Beta: {BETA}
  VAE loss  : MSE(sum/B) + beta * KL(sum/B)   [BUG-4 FIXED: balanced ELBO]
  Lyr loss  : 1 - cosine_similarity(z_lyr, z_audio.detach())
              [BUG-5 FIXED: cosine replaces MSE to preserve geometry]
  Optimisers: separate Adam for VAE and LyricsEncoder
              [BUG-5 FIXED: decoupled to prevent cross-modal gradient leakage]

Lyrics strategy
  10 genre-specific text descriptions embedded with sentence-transformers
  -> 10 distinct 384-dim vectors  [BUG-2 FIXED: was 5 shared mood prototypes]

Data
  Missing spectrograms excluded from training   [BUG-1 FIXED: were zero-filled]

Clustering
  K-Means         (k=10)
  Agglomerative   (k=10, Ward linkage)
  DBSCAN          (eps = elbow of k-NN curve)  [BUG-6 FIXED: was 15th percentile]
  -> {n_clusters_db} clusters found, {n_noise_db} noise points

Evaluation
  evaluate_clustering re-encodes true_labels internally  [BUG-7 FIXED]
  Comparative analysis uses 'PCA (spec) + K-Means'       [BUG-8 FIXED]
""")
print('\n=== Final metrics table ===')
print(results_df[['method', 'n_clusters', 'silhouette', 'davies_bouldin', 'ARI']].to_string(index=False))